### ISSUE TITLE
Docs on nested subtypes need example of unwrapping

### ISSUE THREAD

**Issue by carltongibson** [elm/compiler#1451]
Hi. 

This is for ELM 0.17.x and [the documentation on recursive eliminating recursive type aliases](https://github.com/elm-lang/elm-compiler/blob/0.17.1/hints/recursive-alias.md#less-obvious-but-nicer)

**Issue**: the docs show how to avoid the compiler error but they do not show how to unwrap the nested subtype 

The example from the docs is:

```
type alias Comment =
  { message : String
  , upvotes : Int
  , downvotes : Int
  , responses : Responses
  }

type Responses = Responses (List Comment)
```

All that is said re accessing the `responses` is _"...you only have to do some unwrapping in the cases where you are doing something recursive..."

This leads to, _"OK, but how do I do that?"_ 🤔

Below that paragraph is needed an example of unwrapping the responses back to a `List Comment`. 

I have something like this: 

```
unwrapResponses : Responses -> List Comment
unwrapResponses responses =
    case responses of 
        Responses comments -> comments
```

I'm happy to do a PR, but is this the canonical answer? (It seems a little clumsy.)

Thanks.

**Comment by mgold** [comment]
When you define a union type with only one case, it's possible to do

```elm
unwrapResponses (Responses comments) =
```

Essentially, you're doing a pattern match in the argument list, and because there's only one you know it cannot fail. You can't use this trick, for example, on a `Maybe`; you'd use a case analysis exactly as you have above.
