### ISSUE TITLE
Generated code make javascript debugging difficult, because return value not put in var

### ISSUE THREAD

**Issue by jmonasterio** [elm/compiler#1507]
When compiling to HTML, the generated code throws away the unused return value from fullscreen(). So this value is not available to examine in the debugger.

This code is at the bottom of the compiled HTML file:

```
.call(this);
</script></head><body><script type="text/javascript">Elm.MyApp.fullscreen()</script></body></html>

```

Putting the return value in a global variable would give access to the information when "watching" in debugger.
`
var app = Elm.FcpaActivation.fullscreen();`

In particular I want to see this in a watch window: app.ports
`

**Comment by evancz** [comment]
In the development branch, generated HTML always produces an `app` value. It will be out with the next release of Elm.

Thank you for the report!
