### ISSUE TITLE
Cannot access record field from function prefixed with module name.

### ISSUE THREAD

**Issue by panthus** [elm/compiler#1549]
Elm version 0.18

```elm
module Child exposing (..)

function = { x = 2 }

module Parent exposing (..)

import Child

broken = Child.function.x
```

The code above results in the following error message:

```
-- NAMING ERROR ----------------------------------------------------- Parent.elm
Cannot find variable `Child.function.x`.
11| broken = Child.function.x
                  ^^^^^^^^^^
No module called `Child.function` has been imported.
Detected errors in 1 module.
```
The error happens when trying to access a field of a record that is returned by a function when prefixing the function with the module name. If the function is not prefixed with the module name it works as expected.

**Comment by jvoigtlaender** [comment]
Please check existing open issues, in particular those marked "meta". I think what you report here is already recorded.

**Comment by jvoigtlaender** [comment]
Can't find it in an open myself, though I'm sure I've encountered it before. Hmm.

**Comment by pzolla** [comment]
Is there any discussion on this being fixed?

**Comment by zwilias** [comment]
https://github.com/elm-lang/elm-compiler/issues/1509#issuecomment-267798183

**Comment by pzolla** [comment]
When Evan refers to "new parser" is he referring to 0.19?  Or is this something that should have been fixed in current version?

**Comment by zwilias** [comment]
0.19 indeed :)

**Comment by evancz** [comment]
Looks like this is possible with 0.19
