### ISSUE TITLE
An error in a package is always reported as an elm-package.json issue

### ISSUE THREAD

**Issue by eeue56** [elm/compiler#1608]
## What's wrong

A package is published containing code that works independently.  However, if the package is imported, and the package fails to compile due to a bug like https://github.com/elm-lang/elm-compiler/issues/1094, then an incorrect error is reported. 

Example repo: https://github.com/stoeffel/rocket-issue

The error that is reported is like this:

```
Problem in dependency mdgriffith/style-elements 3.2.2

The elm-package.json constraints of ‘mdgriffith/style-elements’ are probably
letting too much stuff through. Definitely open an issue on the relevant github
repo to get this fixed and save other people from this pain.

In the meantime, take a look through the direct dependencies of the broken
package and see if any of them have had releases recently. If you find the new
thing that is causing problems, you can artificially constrain things by adding
some extra constraints to your elm-package.json as a stopgap measure.
```

This is misleading, as the actual error is because this package did not compile successfully due to the fact it contains `=>`, and another package defined `=>` as infix.

## Current debugging approach

Right now, the easiest way to debug is to add the `src` directory of a given package to the parent project -- hence treating it as a first-class citizen, and getting the real compile error out.

## Fix

I don't really see this being an issue in the future. Would be great to get the child-package error though. This is one weird edge case where it is possible to run into this. Just documenting this so that I have somewhere to point people to in the future.

**Comment by evancz** [comment]
I am not 100% certain, but I think error messages are still pretty vague when they are in dependencies.

In this case, it seems like a separate bug is causing an error message that is not correct.

I think accounting for compiler bugs like that will just make it easier to start programming in downloaded packages as if that is intended behavior. I think that is the bigger downside, so I'm currently planning to keep the behavior the same here.
