### ISSUE TITLE
Transitive dependencies promoted, but cache not updated

### ISSUE THREAD

**Issue by Janiczek** [elm/compiler#1710]
### SSCCE:

**elm.json**
```json
{
    "type": "application",
    "source-directories": [
        "src"
    ],
    "elm-version": "0.19.0",
    "dependencies": {
        "elm-lang/core": "6.0.0"
    },
    "test-dependencies": {},
    "do-not-edit-this-by-hand": {
        "transitive-dependencies": {
          "elm-lang/json": "1.0.0"
        }
    }
}
```
**src/Main.elm**
```elm
module Main exposing (main)

import Json.Decode
import Platform


main : Program () () ()
main =
    Platform.worker
        { init = \() -> ( (), Cmd.none )
        , update = \() () -> ( (), Cmd.none )
        , subscriptions = \() -> Sub.none
        }
```

1. `elm make src/Main.elm` :arrow_right: error saying I should `elm install elm-lang/json`
2. `elm install elm-lang/json` :arrow_right: moves it from transitive deps to deps
3. `elm make src/Main.elm` :arrow_right: the same error, **instead of compiling as expected**
4. `rm -rf ./elm-stuff && elm make src/Main.elm` :arrow_right: compiles!

EDIT: it was not needed to `rm -rf ~/.elm`, removed it from the steps to reproduce.

**Comment by evancz** [comment]
Thank you for the excellent issue! I was able to fix this locally with that commit!
