### ISSUE TITLE
Map.! when --debug with model in separate module

### ISSUE THREAD

**Issue by Janiczek** [elm/compiler#1712]
### Invocation and error
`elm make --debug src/Main.elm`
`Map.!: given key is not an element in the map`

### Weird behaviour:
1) if I merge the files, it suddenly works
2) touching `Types.elm` and then compiling works, but touching `Main.elm` and then compiling breaks (edited)

### Main.elm
```elm
module Main exposing (main)

import Browser
import Html
import Types exposing (..)

main : Program () Name ()
main =
    Browser.embed
        { init = \_ -> ( Name "", Cmd.none )
        , update = \_ model -> ( model, Cmd.none )
        , view = \_ -> Html.text ""
        , subscriptions = \_ -> Sub.none
        }
```
### Types.elm
```elm
module Types exposing (..)

type Name
    = Name String
```

**Comment by evancz** [comment]
Found it. Thank you!
