### ISSUE TITLE
Extensible Records with Multiple Type Arguments

### ISSUE THREAD

**Issue by AesaKamar** [elm/compiler#1717]
I would like to be able to use extensible records to model my data in a slightly more generalized way. 

I'm trying to do something of the form: 
```
type alias PointLike =
    { x : Float
    , y : Float
    }


type alias HasPicture =
    { imgHref : String }


type alias GraphedImage coord img =
    { coord
        | coord : PointLike
    , imgUrl
        | imgUrl : HasPicture
    }
```
 
However,  I am unable to express a `type alias` as having more than one type parameter. 
 
Is there an existing pattern that would allow me to do this?
Or maybe I'm missing some syntax? 
Or is this explicitly disallowed for some justifiable reason?

**Comment by avh4** [comment]
Hi! future questions like this should go to Slack or Discourse:  see http://elm-lang.org/community

In this case, I think the following will do what you want
```
type alias GraphedImage base =
    { base
        | coord : PointLike
        , imgUrl : HasPicture
    }
```

**Comment by evancz** [comment]
Thanks @avh4!
