### ISSUE TITLE
Proposed "Redacted" keyword to flag module members as private

### ISSUE THREAD

**Issue by utricularia** [elm/compiler#1719]
It has been noted before that manually exposing the "public" members of a module can be cumbersome in cases where the number of "private" functions is small relative to the number of public ones. What I would like to propose is the addition of a "redacting" keyword which acts as an override to the exposing keyword, effectively making private any members which are listed as redacted. 

Ex: 

module mymodule exposing (..) redacting (privateFunc1, privateFunc2) -- Would expose all members except privateFunc1, privateFunc2 

module mymodule exposing (publicFunc1, privateFunc1) redacting (privateFunc1, privateFunc2) -- Would expose publicFunc1 but not privateFunc1 (Perhaps a compiler error/warning would be appropriate here?)

Note: In the spirit of full disclosure, the following was suggested when I asked about this in the elm-lang slack channel and seems like a very good way to work around this. I can still see the use case for having a redaction keyword and would still like to submit this proposal but for anyone looking for an answer to this, it seems like a good way to go:

Julian Antonielli [2:46 PM]
@Utricularia Can't you just do something like `module MyModule exposing (..)` with the public stuff, and then `import MyModule.Internal`with the private stuff? (edited)

**Comment by evancz** [comment]
Normally @process-bot leaves [this note](https://github.com/process-bot/contribution-checklist/blob/master/issues.md), but I think I need to update the bot!

I prefer to track bugs in issues. If we tracked feature requests as well, it can be quite distracting and the issues would get cluttered really quickly. That said, I do not think I would make a change like this. I think it is best to be explicit, and I would want to explore how nice things can be with editor plugins before changing the language itself.
