### ISSUE TITLE
Compiler produces invalid JavaScript for multiline strings if input file uses CRLF line endings

### ISSUE THREAD

**Issue by ianmackenzie** [elm/compiler#1720]
SSCCE:

```elm
module Main exposing (..)

{-| Make sure to save with Windows line endings!
-}

import Browser
import Html exposing (Html)


multilineString : String
multilineString =
    """Multiple
line
string
"""


main : Program () () ()
main =
    Browser.staticPage (Html.text multilineString)
```

Save this using CRLF line endings, and the resulting HTML will have the string literal split across multiple lines, leading to a JavaScript syntax error; it should look something like

```javascript
var author$project$Main$multilineString = 'Multiple
\nline
\nstring
\n';
```

If instead the file is saved with Unix line endings, the output looks like

```javascript
var author$project$Main$multilineString = 'Multiple\nline\nstring\n';
```

I am (as you might guess!) on Windows 10 using Elm 0.19 (second alpha).

Note: make sure your editor doesn't auto-convert to LF on save, or is configured to run `elm-format` on save (which looks like it also normalizes to LF). This bug was frustrating to track down because I had that setup, so the issue would only trigger on freshly checked out files (Git was configured to check out as CRLF), but then would disappear as soon as I made any change to the files in question (since they would at that point silently get switched to LF).

**Comment by evancz** [comment]
Thanks for the great report! The fix will produce the following JS:

```javascript
var author$project$Main$multilineString = 'Multiple\r\nline\r\nstring\r\n';
```

**Comment by lydell** [comment]
This is what it compiles to in Elm 0.18 for me (tested on Ubuntu 18.04):

```js
var _user$project$Main$multilineString = 'Multiple\r\nline\r\nstring\r\n';
```

<details>
<summary>Similar Elm 0.18 program with CRLF</summary>

```elm
module Main exposing (..)

{-| Make sure to save with Windows line endings!
-}

import Html exposing (Html)


multilineString : String
multilineString =
    """Multiple
line
string
"""


main : Html msg
main =
    Html.text multilineString
```

</details>

elm-format converts the CRLFs to LF, which technically changes the meaning of the program (the string contents has changed), so perhaps we should open an issue for elm-format as well ... or should Elm compile `\r\n` to `\n` in multiline strings? Perhaps that could help prevent confusing bugs. CoffeeScript works like that, btw.

**Comment by avh4** [comment]
Related elm-format discussion was here: https://github.com/avh4/elm-format/issues/74#issuecomment-267775197, but apart from the bug that was fixed there, no one else has logged any issues related to eol handling on Windows.

**Comment by lydell** [comment]
Cool, thanks! Looks like we're all good then.

**Comment by ianmackenzie** [comment]
I tried looking for (relatively) authoritative references that specifically discussed handling of \r and \n in multiline string literals, but couldn't find a lot...so far it looks like in C# ["Even carriage returns and line feeds can appear in the literal"](http://csharpindepth.com/Articles/General/Strings.aspx) while [the Swift book](https://books.google.com/books?id=ZU0xDwAAQBAJ&printsec=frontcover#v=onepage&q&f=false) is pretty explicit: "Line endings in a multiline string literal are normalized to use the line feed character. Even if your source file has a mix of carriage returns and line feeds, all of the line endings in the string will be the same." (I was able to read that text using Google Books, but you may hit reading limits.)

Would it be helpful for me to just try things out in various languages that support multiline string literals and see what happens? (I'd be a bit worried that if the behavior isn't specified somewhere, then it could just be an accident of the implementation instead of a conscious choice.) The Swift example is the only place I could find where it looked like someone had actually put some deliberate thought into the issue.

**Comment by harrysarson** [comment]
> should Elm compile \r\n to \n in multiline strings?

Creating multiline JS strings using backticks results in `\n` (and only `\n`) inserted at the newlines. Running the following on windows with node v9:

### multiline.js
``` js
module.exports = `first line
second line`;
```
``` bash
$ node
> require('./multiline.js')
'first line\nsecond line'
> fs.readFileSync('./multiline.js', 'utf8')
'module.exports = `first line\r\nsecond line`;'
```

I would argue that elm should do the same.
