### ISSUE TITLE
Runtime error sending the unit type over a port (Elm->JS)

### ISSUE THREAD

**Issue by dmattia** [elm/compiler#1731]
### Expectation
sending `()` over a port to javascript would continue to work as it did in 0.18. I frequently sent the empty tuple when I wanted to send a message over a port without content. 

### What is happening
sending `()` over a port compiles, but causes the front end to throw a runtime exception.

### To Reproduce
- SSCCE: https://gist.github.com/dmattia/e7adcd0e1900bb3d5f0e19ce1413393a
- latest 0.19 binary
- latest version of chrome

Thanks for all the work you've done on 0.19, so far it's worked great for me!

**Comment by evancz** [comment]
Got confirmation from @pdamoc that this is fixed in the latest version of things. Thanks for the report!
