### ISSUE TITLE
"Expected" type appears same as Actual type in error

### ISSUE THREAD

**Issue by Erudition** [elm/compiler#1739]
The following error message can lead to much frustration and probably should not be obtainable.
```bash
$ elm-make BugReport.elm
-- TYPE MISMATCH ------------------------------------------------- BugReport.elm

The 2nd argument to function `map` is causing a mismatch.

12|   Decode.map OnDayOf (Decode.field "moment" decodeMoment)
                          ^^^^^
Function `map` is expecting the 2nd argument to be:

    Decoder Moment

But it is:

    Decoder Moment

Hint: I always figure out the type of arguments from left to right. If an
argument is acceptable when I check it, I assume it is "correct" in subsequent
checks. So the problem may actually be in how previous arguments interact with
the 2nd.

Detected errors in 1 module.    
```
As you can see, the Compiler suggests your coded type "Moment" is incompatible with the one it should be, "Moment" - the (apparently) same type - which is even worse for one's sanity than the times when it says something like "String" is incompatible with [some type alias of String].

The example below includes two rookie mistakes (I think) that I only realized I made when I was trying to isolate this bug into an SSCE; I've encountered the bug before, but this is the only code I still have that produces it. I'm sure there is an even more minimal way to trigger it than this example. 

Working Minimal SSCE code:
BugReport.elm
```elm
module BugReport exposing (..)

import Json.Decode as Decode exposing (..)

import BugReport2 exposing (..)

type alias Moment = String


decodeOnDayOf : Decoder MomentOrDay
decodeOnDayOf =
  Decode.map OnDayOf (Decode.field "moment" decodeMoment)


decodeMoment : Decode.Decoder Moment
decodeMoment = string
```

BugReport2.elm
```elm
module BugReport2 exposing (..)

type Moment = String
type MomentOrDay = AtExactly Moment | OnDayOf Moment
```

My excuse for providing a bug example relying on simple coding mistakes is that these mistakes are not caught by the compiler (Yet they really should be - perhaps good for two more bug reports) and because the error should not be written this way either way.  Again, the example code produces the above error and the above error only.

* Mistake 1: Multiple definitions for the same example type `Moment`, albeit among different modules so there is no warning like there would be otherwise.
* Suspected Mistake 2: ``type Moment = String`` instead of ``type alias Moment = String``. I now suspect this is bad coding, oops! I did not arrive at this code by accidentally leaving out "alias", however, rather I removed intentionally at one point to see if it would make an error go away (probably one where it said "expecting Moment but I got a String" or the like) and it did. 

For the second there was no warning either, and I'd say it's a major newbie trap. I did not change it to ``type`` because I thought it meant the same thing as ``type alias``, but rather because I thought it didn't. But my current guess is that it's more different than I thought: ``type Moment= String`` is actually defining a type named Moment along with its possible values, of which there happens to be only one, and that one happens to have the name String (the same as a built-in type). Should this even be allowed?

If I'm right about that, then I guess what's really happening is this:
```
Function `map` is expecting the 2nd argument to be:

    Decoder BugReport.Moment

But it is:

    Decoder BugReport2.Moment
```
Normally, Elm's errors will do this automatically (be as specific as needed to disambiguate when there are naming conflicts), so I'm sure the original error message is not the desired behavior.

**Comment by evancz** [comment]
Thanks for the report! In the development version of the compiler, this is the error I see:

![screen shot 2018-07-30 at 1 58 51 pm](https://user-images.githubusercontent.com/1658058/43414457-c7129382-9400-11e8-806e-077b810132b8.png)

So this should be fixed in the next release!

**Comment by Erudition** [comment]
Yesssss

**Comment by evancz** [comment]
We can  potentially warn about that. Making design changes is quite complex, but I will put it in my list of sharp edges.
