### ISSUE TITLE
Reusing variable name in (let inside case inside let) gives runtime error, undefined value in other case branches

### ISSUE THREAD

**Issue by ChickenProp** [elm/compiler#1740]
Minimal example, that currently works at http://elm-lang.org/try:

```elm
import Html exposing (text)

main = text <|
  let a = 1
      b = case True of
        False -> let a = "foo" in a
        True -> toString a
  in b
```

This should show "1" but it actually shows "\<internal structure>". Looking at the compiled javascript, the problem is that the generated code has structure like

```javascript
var a = 1;
var b = function () {
  if (false) { var a = "foo"; return a }
  else { return Basics$toString(a); }
}();
return b;
```

where the `a` inside `if (false) { ... }` shadows the definition that the `else { ... }` block is trying to refer to. If I rename either `a` to something else, the problem goes away; if I move the case statement to the `in` (i.e. replace `b` with its definition) it also goes away. If instead of `a=1` I define the outer `a` as a string, and don't use `toString`, then instead of "\<internal structure>" I get "undefined".

**Comment by evancz** [comment]
In the next release of Elm, variable shadowing like this will not be permitted. So folks get an error based on the syntax itself, and it cannot reach the code generation phase anymore. So it should be resolved by that. Thank you for the nice report of the possible current issue though!
