### ISSUE TITLE
`elm reactor` gives a vague error on circular dependencies

### ISSUE THREAD

**Issue by trenneman** [elm/compiler#1741]
Ran the following with Elm 0.19 on Arch Linux using Chrome Version 68.0.3440.75 (Official Build) (64-bit).

```
$ git clone --single-branch -b elm-reactor-circular-dependencies git@github.com:trenneman/sscce.git
$ elm build
Dependencies loaded from local cache.
Dependencies ready!                
-- IMPORT CYCLE ----------------------------------------------------------------

Your module imports form a cycle:

    ┌─────┐
    │    Bar
    │     ↓
    │    Foo
    └─────┘

Learn more about why this is disallowed and how to break cycles
here:<https://elm-lang.org/0.19.0/import-cycles>

$ elm reactor
```
While `elm make` gives the correct error, loading the page at http://localhost:8000/src/Main.elm returns: `Problem with the value at json.path: null Expecting a STRING`:

![elm-reactor-circular-dependency](https://user-images.githubusercontent.com/2738701/43382945-be69029c-93d9-11e8-9797-426b1290fab2.png)

**Comment by evancz** [comment]
When I clone everything and run `elm reactor`, I see the following in the browser:

![screen shot 2018-07-30 at 2 56 24 pm](https://user-images.githubusercontent.com/1658058/43417371-cd29c648-9408-11e8-9722-2f91ae0e147a.png)

I do not know what `elm build` is though, so perhaps that is doing something odd that is getting picked up by `elm reactor`. Please open a new issue if you find an SSCCE that reproduces what you saw.
