### ISSUE TITLE
REPL fails on any expression if current directory does not contain `elm.json`. Message: "elm: Map.!: given key is not an element in the map"

### ISSUE THREAD

**Issue by timbuckley** [elm/compiler#1747]
Elm REPL crashes on any expression entered when working directory is empty. Initial investigation indicates that the REPL requires an `elm.json` file in the current directory, as adding a well-formed `elm.json` via `elm init` seems to resolve the issue.

Recreated on the last two elm `0.19` binaries, but not on `0.18`:
```bash
$ md5 elm-new
MD5 (elm-new) = e7463e4e7e4d046e0193bc3b77215660
$ md5 elm-prev
MD5 (elm-prev) = c0fed274d69cf64eb5e0bf2380e08a86
```

## SSCCE

When the working directory is empty, the REPL fails on any expression attempted.

```elm
$ ls -A
$ elm-new repl
---- Elm 0.19.0 ----------------------------------------------------------------
Read <https://elm-lang.org/0.19.0/repl> to learn more: exit, help, imports, etc.
--------------------------------------------------------------------------------
> 1
elm: Map.!: given key is not an element in the map
CallStack (from HasCallStack):
  error, called at libraries/containers/Data/Map/Internal.hs:603:17 in containers-0.5.10.2:Data.Map.Internal
$
```

Problem disappears once I do `elm-new init` in the current directory:

```elm
$ elm-new init
<truncated>
$ ls -A
elm.json	src
$ elm-new repl
---- Elm 0.19.0 ----------------------------------------------------------------
Read <https://elm-lang.org/0.19.0/repl> to learn more: exit, help, imports, etc.
--------------------------------------------------------------------------------
> 1
1 : number
```

Seems to be a hard requirement on the existence of an `elm.json` file locally.

```elm
$ rm elm.json
$ elm-new repl
<truncated>
> 1
elm-new: Map.!: given key is not an element in the map
CallStack (from HasCallStack):
  error, called at libraries/containers/Data/Map/Internal.hs:603:17 in containers-0.5.10.2:Data.Map.Internal
```

I consider this a regression, since `0.18` does not have this requirement.

```elm
$ ls -A
$ elm repl
---- elm-repl 0.18.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> 1
1 : number
> :exit
```

**Comment by rtfeldman** [comment]
I get the same crash when using `elm repl` on packages (but not on applications), even if there is a valid `elm.json` present.

Specifically, I can run `elm make` and get `Success! Compiled 5 modules` on the package, and then if I run `elm repl` it crashes with `Map.!: given key is not an element in the map` as soon as I try to evaluate any expression.

**Comment by evancz** [comment]
I made some changes where JSON stuff was needed for the `toString` implementation for the "print" part of the REPL. So the fix above should fix when you are outside of any `elm.json` directory. I do not think it fixes the package case though.
