### ISSUE TITLE
Building executable 'elm' for elm-0.19 fails on OpenBSD 6.3 (ghc-8.2.2)

### ISSUE THREAD

**Issue by romanzolotarev** [elm/compiler#1750]
Building `elm-0.19` on OpenBSD 6.3 -stable with ghc-8.2.2p1 and cabal-install-2.0.0.1.

```
$ uname -srv
OpenBSD 6.3 GENERIC.MP#8
$ cabal --version
cabal-install version 2.0.0.1
compiled using version 2.0.1.0 of the Cabal library 
$ ghc --version             
The Glorious Glasgow Haskell Compilation System, version 8.2.2
```
Due to W^X restrictions, `.cabal` and `elm/compiler` moved to `/usr/local` (mounted with `wxallowed`).

```
$ doas pkg_add ghc cabal-install
$ doas mkdir -p /usr/local/{cabal,cabal/build}
$ doas chown -R $(whoami):wheel /usr/local/cabal
$ rm -rf ~/.cabal
$ ln -s /usr/local/cabal ~/.cabal
$ alias cabal='env TMPDIR=/usr/local/cabal/build/ cabal'
$ cabal update
$ cd /usr/local/
$ git clone https://github.com/elm/compiler elm
$ cd elm
```

When building Elm, the core dump dropped and cabal exits.

```
$ cabal install
Resolving dependencies...
Configuring elm-0.19.0...
Building elm-0.19.0...
Failed to install elm-0.19.0
Build log ( /home/user/.cabal/logs/ghc-8.2.2/elm-0.19.0-6zRUDcfBIu51Yvs2whdnMK.log ):
cabal: Entering directory '.'
Configuring elm-0.19.0...
Preprocessing executable 'elm' for elm-0.19.0..
Building executable 'elm' for elm-0.19.0..
[161 of 167] Compiling Develop.StaticFiles ( ui/terminal/src/Develop/StaticFiles.hs, dist/build/elm/elm-tmp/Develop/StaticFiles.o )
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
elm-0.19.0-6zRUDcfBIu51Yvs2whdnMK failed during the building phase. The
exception was:
ExitFailure (-10)
$
```

P.S. [How to install OpenBSD in VM](https://www.romanzolotarev.com/openbsd/).
Or ping me with your SSH public key I'll provide access to OpenBSD instance.

**Comment by evancz** [comment]
I cannot provide support for people building from source in issues. There are community members with experiences that can help you, so I recommend asking about it on the Elm slack. I suspect the #compiler channel will have the answer!

**Comment by romanzolotarev** [comment]
Thank you for your quick response and for the pointer.

**Comment by tigp** [comment]
@romanzolotarev have you installed Elm on OpenBSD finally?

**Comment by romanzolotarev** [comment]
Yes, but without Reactor. https://twitter.com/romanzolotarev/status/1032299983180128257

**Comment by tigp** [comment]
Thanks @romanzolotarev for your help!

**Comment by j340m3** [comment]
I'm sorry for resurrecting this old issue, but could you (@romanzolotarev) provide everyone access to your patch? I'm trying to get it running on OpenBSD, too. But I can't access this file since I don't have account on slack.
