### ISSUE TITLE
REPL help commands missing ':' and language is a bit confusing.

### ISSUE THREAD

**Issue by jweir** [elm/compiler#1755]
When opening up the repl for 0.19 it took me a while to figure out how to exit.

See:

https://github.com/elm/compiler/blob/091fa6b3aa82c3b2d406260117096876566a1ace/ui/terminal/src/Repl.hs#L331

Shouldn't this read something like:

```
D.black $ D.fromString $ "Read " <> D.makeLink "repl" <> " to learn more. Available commands :exit, :help, and :reset"
```

**Comment by evancz** [comment]
The link tells you more about those topics. Unfortunately, that is in the binary so we can not change it in 0.19.
