### ISSUE TITLE
breadcrumbs navigation in elm reactor is broken

### ISSUE THREAD

**Issue by pdamoc** [elm/compiler#1758]
Steps to reproduce: in a new folder, run `elm init`, run `elm reactor`, navigate to `src` folder, click `src` link  in the breadcrumb.  It displays a "This site can’t be reached" error in Chrome on OSX. 

The cause of the error is an extra `/` added at the beginning of the link (e.g `//src` instead of `/src`) 

Most likely culprit is 
https://github.com/elm/compiler/blob/master/reactor/src/Index/Navigator.elm#L22

It should be `(makeLinks root dirs "" [])`.

**Comment by jhrcek** [comment]
Just encountered the same issue and wanted to suggest the same fix :D
