### ISSUE TITLE
elm install command gives error with TODO when using improper arguments

### ISSUE THREAD

**Issue by stephenreddek** [elm/compiler#1759]
macOS 10.13.6
Elm 0.19.0 installed from mac installer

To reproduce in terminal (in an empty directory or an elm project):
* `elm install sscce`

result:
```
elm: TODO show possible arg configurations
CallStack (from HasCallStack):
  error, called at ui/terminal/src/Terminal/Args/Error.hs:281:13 in main:Terminal.Args.Error
```

**Comment by kachkaev** [comment]
It's a bit suprising to see regressions in install behaviour after the official release of elm 0.19. Besides the issue above, it's no longer possible to `elm install author/project --yes` to avoid a prompt in stdin (which requires workaround if `elm install` is called by some software. In addition to that, there is no way to install a specific version, i.e. `elm install author/project 1.2.3 --yes` or `elm install author/project --yes --version=3`.

Both cases are crucial for our [litvis project](https://github.com/gicentre/litvis/), we people declare elm dependencies in markdown frontmatter like this:

```markdown
---
elm:
  dependencies:
    author/project: latest
    author2/project2: 42
---
```

example: [lunarEclipse.md](https://github.com/gicentre/litvis/blob/master/examples/lunarEclipse.md) + [raw markdown](https://raw.githubusercontent.com/gicentre/litvis/master/examples/lunarEclipse.md)

**Comment by evancz** [comment]
With 0.19.1 I am seeing the following output:

```
I am having trouble with this argument:

    sscce

It is supposed to be a <package> value, like one of these:

    elm/json
    elm/http
    elm/random

```

Thank you for the report!
