### ISSUE TITLE
How to uninstall elm?

### ISSUE THREAD

**Issue by screendriver** [elm/compiler#1760]
How can I uninstall `elm`? I downloaded the [installer-for-mac.pkg](https://github.com/elm/compiler/releases/download/0.19.0/installer-for-mac.pkg) from [here](https://guide.elm-lang.org/install.html) and saw afterwards that it is also released on npmjs.com

Because I prefer to install `elm` as a global npm package I want to uninstall it first. But how? 🤔

**Comment by evancz** [comment]
All it does is put the `elm` binary in `/usr/local/bin`, so you can delete it from there if you want. If my memory is correct, it doesn't do anything else on Mac.
