### ISSUE TITLE
`elm reactor` not recompiling changes

### ISSUE THREAD

**Issue by psfblair** [elm/compiler#1778]
Elm 0.19.0 installed twice - once via npm into ~/.npm-global, once using package installer download linked at https://guide.elm-lang.org/install.html
macOS 10.13.6
Safari browser

To reproduce: 
1. Within an elm project that uses ```main : Program () Model.Model Msg.Msg``` with ```Browser.element``` at the top level, run ```elm reactor```
2. Access http://localhost:8000/index.html  
3. Introduce a typo into the program and save it.
4. See no output on the console running ```elm reactor```
5. Reload the page in the browser.
6. See no change in ```index.html``` and no output on the console running ```elm reactor.```

**Comment by evancz** [comment]
When you run `elm make src/Main.elm` it produces a `index.html` file.

When you use `elm reactor` it lets you browse files:

- If it is a `.elm` file, it will compile it on refresh.
- If it is a `.json` file, it just shows it.
- If it is a `.jpg` file, it just shows it.
- If it is a `.html` file, it just shows it.
- etc

So I think you are expecting a certain workflow to work, but that is not the particular workflow that is supported at this time.
