### ISSUE TITLE
Add a --ignore-debugs flag for optimized code generation

### ISSUE THREAD

**Issue by JDemler** [elm/compiler#1781]
It would be awesome if there was a flag that would ignore calls to `Debug` when compiling with the `--optimize` flag. Currently compilation is aborted when calls to `Debug` occur.

Use case:
There are some errors that can fail silently in production, but when debugging or developing its nice to be able to see them.

For example: 
- Unhandled match case in "SPAs" `Main.update` [like in the example](https://github.com/rtfeldman/elm-spa-example/blob/master/src/Main.elm#L275)
I used to have a `Debug.log` "Unhandled match case in Main.update" there. When adding a new page and not hooking it up correctly its a real lifesaver.

- Serialization Errors. Usually happen when backend and frontend serialization code is not in sync during active development. Saves a lot of time if they are just logged to the console

Of course that wouldn't be a good idea for packages that get published or as a default. 
But I really like to keep the`Debug` calls in a rapidly changing "SPA" and still be able to develop and publish on the same branch.

**Comment by evancz** [comment]
I am not sure what to think about this idea without asking around to other folks with production code. My intuition is that this isn't the kind of thing I want to be changing in `0.19.x` releases, so I think it makes sense to get more discussion about this from other perspectives and figure out how to share them on discourse or elm-dev mailing list.
