### ISSUE TITLE
TODO in elm publish --help

### ISSUE THREAD

**Issue by pzp1997** [elm/compiler#1786]
There is a TODO in the output for `elm publish --help`.

SSCCE:
```
$ elm publish --help

The `publish` command publishes your package on <https://package.elm-lang.org>
so that anyone in the Elm community can use it.

    elm publish

Think hard if you are ready to publish NEW packages though!

(Ommited 2 paragraphs for brevity.)

Check out <TODO> for guidance on how to create great packages!
```

Version Info:
Elm 0.19.0 (installed using Homebrew)
macOS 10.11.6

**Comment by andys8** [comment]
Still the case.

**Comment by evancz** [comment]
Thank you for the report! This should link to https://package.elm-lang.org/help/design-guidelines in Elm 0.19.1.

**Comment by evancz** [comment]
https://github.com/elm/compiler/blob/master/terminal/src/Main.hs#L269
