### ISSUE TITLE
Outdated/wrong elm make help text

### ISSUE THREAD

**Issue by jpincas** [elm/compiler#1791]
When running `elm make --help`, the following help text is displayed:

![screen shot 2018-09-07 at 11 17 06](https://user-images.githubusercontent.com/17711012/45211169-e19d8900-b291-11e8-8479-168892dcceca.png)

I believe it should state that the output will go into an `index.html`

**Comment by evancz** [comment]
Nice catch! Made an edit that should come out with 0.19.1. Thank you!
