### ISSUE TITLE
Why elm runs from body in index.html instead of head?

### ISSUE THREAD

**Issue by nullbio** [elm/compiler#1794]
When using elm make the elm code is placed in the body section of index.html. Since elm also contains all of the html, I'm curious why head would not be a better place for this? 

Traditionally, placing scripts in body would allow you to load stylization first. This made it appear like the page loaded faster (visually it was, but operationally it wouldn't work until the js was retrieved). However elm is different because there's no separation of html and javascript, so this doesn't seem to apply any longer. Am I missing something here? Thanks.

**Comment by timbuckley** [comment]
One reason is that, in some cases, Elm is supposed to only control a single DOM element, as with `Browser.element`, which requires of course that the requisite DOM node is already rendered on the page, and so the script has to be placed on the bottom.
