### ISSUE TITLE
Force colourful output from Elm make

### ISSUE THREAD

**Issue by lpil** [elm/compiler#1803]
I'm running `elm make ...` as a subprocess in my development web server. I would like to be able to see colourful output but the `elm` program doesn't output colours when run this way.

Is it possible to force colourful output? Other programs I've used check for a `--color` flag or a `COLOR` environment variable.

Thanks,
Louis

**Comment by evancz** [comment]
It is not possible to force the ANSI colors at this time.

It would be helpful to document your particular set up. What is running `elm` as a subprocess? Does that thing run subprocesses without hooking them to stdout and stderr for some particular reason? Etc.

**Comment by lpil** [comment]
I'm running it as subprocess in an Elixir web server using the System.cmd/3 function, stdin and stdout are hooked up. I'm using the closing of stdin as the trigger for cleaning up a couple build processes.

**Comment by evancz** [comment]
Try hooking in `stderr` as well. It checks that it's writing to normal buffers, not files.

**Comment by lpil** [comment]
Stdin, stderr and stdout are all hooked up

**Comment by loganmac** [comment]
@lpil You need to connect the process to a "PTY" or "pseudoterminal", and then use that to redirect/copy the output. I'm not sure if Elixir has good faculties for doing this (I couldn't find any), but I've done projects with it in Go.

**Comment by lpil** [comment]
I don't believe this is possible :(
