### ISSUE TITLE
Proposal: Allow Posix to be comparable

### ISSUE THREAD

**Issue by psyCodelist** [elm/compiler#1808]
Hello,

Thanks for all the hard work!

currently we can not compare 2 posix:
posix1 < posix2 throws:
```
I need both sides of (>) to be the same type:
                             if expiryDate > today then
                                    ^^^^^^^^^^^^^^^^^^
The left side of (>) is:
      comparable
But the right side is: 
    Posix
I cannot compare different types though! Which side of (>) is the problem?
Hint: Only ints, floats, chars, strings, lists, and tuples are comparable.
```

**Comment by ryan-senn** [comment]
You are probably aware of it but you can do `Time.toMillis expiryDate > Time.toMillis today` in case someone is wondering.

**Comment by psyCodelist** [comment]
Sure that's what I'm doing right now. But I thought it should be comparable out of the box!

**Comment by ianp** [comment]
I think that this should probably be closed, and added as an additional example under #1008
