### ISSUE TITLE
Inequality operator returns value of wrong type if one operand is 0

### ISSUE THREAD

**Issue by LukeWoodward** [elm/compiler#1810]
In Elm 0.19 the inequality operator `/=` returns incorrect values if one operand is the `Int` value `0`: it appears to return the other operand when it should return `True` or `False`.

SSCCE in the Elm 0.19 REPL:

    ---- Elm 0.19.0 ----------------------------------------------------------------
    Read <https://elm-lang.org/0.19.0/repl> to learn more: exit, help, imports, etc.
    --------------------------------------------------------------------------------
    > 128 /= 0
    128 : Bool

The issue is not reproducible in Elm 0.18, which behaves as expected:

    ---- elm-repl 0.18.0 -----------------------------------------------------------
     :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
    --------------------------------------------------------------------------------
    > 128 /= 0
    True : Bool

I've filed this as a compiler bug because the root cause appears to be bad code generation.  To verify this I wrote the following Elm module:

```elm
module Equality exposing (..)

import Html exposing (Html, div, text)
import Browser

main =
    Browser.sandbox
        { init = 0
        , update = update
        , view = view 
        }
 

update msg model =
    model
    
    
view _ =
    div [] [ text (Debug.toString (128 /= 0)) ]

```

The compiled `index.html` file includes the following lines in the compiled output of the `view` function:
```javascript
				elm$html$Html$text(
				elm$core$Debug$toString(128))
```

I can't reproduce this problem with any type other than `Int`, and I can't reproduce it with two non-zero `Int` values.  I also cannot reproduce any similar problem with the `==` operator.

I'm running Windows 10 version 10.0.17134.285 64-bit.

**Comment by szabba** [comment]
[This](https://ellie-app.com/3qZHyTxDYFBa1) Ellie seems to exhibit the same behaviour.

**Comment by LukeWoodward** [comment]
> [This](https://ellie-app.com/3qZHyTxDYFBa1) Ellie seems to exhibit the same behaviour.

@szabba I don't see why that Ellie exhibits the same behaviour.

All I can see you doing with the `x` value is putting it in `model.x` and then testing the truthiness of that.  Because of this bug `x`, and hence `model.x`, will have the value `96` rather than `True`, but in JavaScript `96` is just as truthy as `True`, so `TRUE` appears.  Because `model.x` is never updated, `TRUE` always appears above the `+1` button.

I would expect this Ellie to behave exactly the same once this bug has been fixed and `x` has the value `True` instead of `96`.

**Comment by szabba** [comment]
I did consider the value `96` visible in the debugger, for a field that is typed `Bool` to be the same issue. Sorry, if that was confusing/unhelpful.

**Comment by terezka** [comment]
Hi! I just wanted to note for future readers that this issue doesn't actually interfere with the functionality. Since the type is supposed to be a boolean, then it will work fine in the rest of the program. The problem can only be discovered by the use of `toString`, which isn't really a problem. :)

**Comment by avh4** [comment]
> The previous version had (0 /= x) and (x /= 0) result in truthy values, rather than the direct true or false value. The truthy values were observable via Debug.toString, so this will fix #1810. It seems there are other case where it can be observed, though I have not seen any reports of those cases.

This can be observed without `toString` by putting the bad bool inside any data structure.  Elm 0.19.0 incorrectly evaluates all of the following to `False`:

```
{ a = 7 /= 0 } == { a = True }
Just (7 /= 0) == Just True
(7 /= 0, True) == (True, True)
[(7 /= 0), True] == [True, True]
```

**Comment by malaire** [comment]
Doesn't even need a data structure, this also evaluates to `False` in Elm 0.19:

    (12 /= 0) == (21 /= 0)

**Comment by evancz** [comment]
For the record, this is due to an optimization that relied on truthiness in JS. That issue https://github.com/elm/compiler/issues/1810 was fixed.

**Comment by ok32** [comment]
Hey. I'm new to Elm and its ecosystem and I'm unfamiliar with the release cycle and stuff. When could we expect a release including this fix? Or maybe a recommended approach is to build the compiler from source? How does it usually go with such notable bugs like this one? Thanks.

@evancz
