### ISSUE TITLE
No elm command in Terminal after fresh install on macOS

### ISSUE THREAD

**Issue by johannesl** [elm/compiler#1812]
How to reproduce:

1) Install macOS High Sierra on a new Macbook / iMac
2) Click "Install" on elm-lang.org
3) Click "Mac - Installer"
4) Open Terminal
5) Try to run "elm"

```
$ elm
-bash: elm: command not found
```

**Comment by johannesl** [comment]
One more detail: macOS upgraded to 10.13.6 and no prompts for further upgrades.

**Comment by evancz** [comment]
Can you try to get help on https://discourse.elm-lang.org/ or on the Elm Slack http://elmlang.herokuapp.com/

If it is a bug, they will help reveal the root and that can be reported in a more specific way.

**Comment by johannesl** [comment]
Will do!
