### ISSUE TITLE
Multi-line strings cause errors to be reported on the wrong line

### ISSUE THREAD

**Issue by harmboschloo** [elm/compiler#1819]
![image](https://user-images.githubusercontent.com/7893506/46558865-c8b6e080-c8ee-11e8-819b-d6616c0131ef.png)

The error is on line 14, but it is reported on line 17. 
The line offset is exactly the same as the number of new lines in the multi-line string.
Using Windows 10, elm 0.19.0.

**Comment by evancz** [comment]
I am pretty sure this is because lines end with `\r\n` on Windows. I think the `\r` is getting counted as a new line as well. Thanks for the report! I'll look into how to fix it!

**Comment by harmboschloo** [comment]
Looks like that's correct. If I change the line endings to `\n` the error is reported on the correct line.
