### ISSUE TITLE
ParcelJS triggering IO error in compiler

### ISSUE THREAD

**Issue by domenkozar** [elm/compiler#1825]
I'm using https://parceljs.org and got this error during save:

```
🚨  /home/ielectric/dev/frontend/src/Main.elm: Compilation failed
elm: /home/ielectric/dev/frontend/elm-stuff/0.19.0/Main.elmi: getModificationTime:getFileTimes:getFileStatus: does not exist (No such file or directory)                                                      
elm: thread blocked indefinitely in an MVar operation

elm: /home/ielectric/dev/frontend/elm-stuff/0.19.0/Main.elmi: getModificationTime:getFileTimes:getFileStatus: does not exist (No such file or directory)                                                      
elm: thread blocked indefinitely in an MVar operation

    at ChildProcess.<anonymous> (/home/ielectric/dev/frontend/node_modules/node-elm-compiler/index.js:149:27)                                                                                                 
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by domenkozar** [comment]
Also got:

```
elm: /home/ielectric/dev/frontend/elm-stuff/0.19.0/CachixApi.elmi: removeLink: does not exist (No such file or directory)
elm: thread blocked indefinitely in an MVar operation

elm: /home/ielectric/dev/frontend/elm-stuff/0.19.0/CachixApi.elmi: removeLink: does not exist (No such file or directory)
elm: thread blocked indefinitely in an MVar operation
```

**Comment by Janiczek** [comment]
@domenkozar This will probably need some code and versions of your tools posted to allow people to reproduce it.

**Comment by domenkozar** [comment]
It happens very rarely for me, I have yet to find a good way to reproduce it reliably.

**Comment by rosensama** [comment]
FWIW, I'm getting it to.   Sorry, I also cannot reproduce on demand.   This is with parcel 1.10.3.

I'll note that it uses rtfeldman/node-elm-compiler if that makes a difference

**Comment by evancz** [comment]
I know that 0.19.0 can have trouble reading cached files when tools are running multiple `elm make` commands simultaneously on the same project. If that is the issue:

1. The next release will use filelock internally to make this impossible.
2. Even without that change, running two `elm make` on the same project at the same time is wasteful and probably will be a perf problem on the side of the 3rd party tooling even after the compiler gets filelock added.

I do not have enough information to be sure this is on the Elm side, so I think the next step would be to get the problem down to an http://sscce.org/ that only involves running Elm commands. Then it will at least be possible to confirm that the changes in 0.19.1 are relevant to this topic.
