### ISSUE TITLE
publish fails with 'your local code is different than the code tagged on Github'

### ISSUE THREAD

**Issue by ericgj** [elm/compiler#1826]
Elm: 0.19.0
OS: ArchLinux (on virtualbox)

Steps taken:
1. `elm bump`
2. `git add -A  && git commit -m "version bump"`
3. `git tag 2.0.1`
4. `git push origin master --tags`
5.  `elm publish`

Fails with "LOCAL CHANGES" error: "Your local code is different than the code tagged on Github"

There are no local changes and the current, tagged, local commit is the same as the commit tagged on Github.

It recommends "If you are sure everything is in order, you can run `git checkout 2.0.1` and publish your code from there".  But that results in the same error.

NB. this is the first 0.19 release of the library if that makes a difference.

**Comment by rlefevre** [comment]
What is the output of the following command?
```
$ git diff-index 2.0.1 --
```

**Comment by ericgj** [comment]
Closing for now, it could be something specific to my machine, will reopen if needed. Thanks again for your help.
