### ISSUE TITLE
Can elm npm installer allow specification of binary sources from other source?

### ISSUE THREAD

**Issue by DamianReeves** [elm/compiler#1827]
I'm attempting to install the new `elm 0.19.0-bugfix2` version from npm using our corporate Artifactory server. The packaging team is balking at doing this since it reaches out for binaries on github. They would like to download the binaries and have the package "redirected" to the binaries housed on our own servers.

Is it possible to extend the npm installer so that it will use an environment variable to locate the OS specific binaries if it is specified? We currently do a similar thing with the electron editor in our firm.

**Comment by bingenito** [comment]
One possibility: 

```
var root =
  process.env.ELM_MIRROR || "https://github.com/elm/compiler/releases/download/" +
  binVersion +
  "/binaries-for-";
```

**Comment by evancz** [comment]
Given the information I have, it seems like the binary can be downloaded with `wget` or `curl` and you can point it directly at your own servers. That seems like a better path than adding complexity to the existing `npm` install. So I will close for now. If there is more information that make using `wget` or `curl` impossible, it may be good to discuss on https://discourse.elm-lang.org/ or https://elmlang.herokuapp.com/ before opening a new issue that describes why that path is not viable.
