### ISSUE TITLE
ELM 0.19 Debug History Export/Import Broken

### ISSUE THREAD

**Issue by dkrasner** [elm/compiler#1828]
###Main Issue###

* Exporting and importing history throws a `Cannot import history` message.
* CSS on the `Cannot import history` message is broken. 

####Basic Example of Error####
```ELM
import Browser
import Html exposing (Html, button, div, text)
import Html.Events exposing (onClick)


main =
  Browser.sandbox { init = init, update = update, view = view }


-- MODEL

type alias Model = Int

init : Model
init =
  0


-- UPDATE

type Msg = Increment | Decrement

update : Msg -> Model -> Model
update msg model =
  case msg of
    Increment ->
      model + 1

    Decrement ->
      model - 1


-- VIEW

view : Model -> Html Msg
view model =
  div []
    [ button [ onClick Decrement ] [ text "-" ]
    , div [] [ text (String.fromInt model) ]
    , button [ onClick Increment ] [ text "+" ]
    ]
```

running ` elm make Main.elm --output=main.html --debug` and exporting/importing history will throw message. 

Note: in 0.18 there is **no** such issue. 

#####Example of Broken CSS####

The CSS in the `Cannot import history` message is not responsive to the page and can break as in the following example. This is fixed by making the top message div responsive; example replacing `height: 600px` with `height: 100%` and related minor changes. 

<img width="568" alt="screen shot 2018-10-15 at 11 18 49 am" src="https://user-images.githubusercontent.com/1154326/47023545-dc074e80-d12d-11e8-9314-696d916f1afd.png">

**Comment by jinjor** [comment]
For the first case, I found the 0.19 debugger exports a wrong JSON file.

```json
{"$":0,"a":{"metadata":{"versions":{"elm":"0.19.0"},"types":{"message":"Main.Msg","aliases":{},"unions":{"Main.Msg":{"args":[],"tags":{"Decrement":[],"Increment":[]}}}}},"history":[null,null,null]}}
```

This JSON causes a decoding error when it is imported. The object is created [here](https://github.com/elm/browser/blob/master/src/Debugger/Main.elm#L281-L285). But the `json` object is [wrapped](https://github.com/elm/json/blob/master/src/Elm/Kernel/Json.js#L413) for the debug mode. So the quick fix would be stringifying `json` before calling kernel function. I attempted that and got the correct JSON.

```json
{"metadata":{"versions":{"elm":"0.19.0"},"types":{"message":"Main.Msg","aliases":{},"unions":{"Main.Msg":{"args":[],"tags":{"Decrement":[],"Increment":[]}}}}},"history":[null,null,null]}
```
However, this looks still broken. The last `[null, null, null]` should be something like `[ Increment, Increment, Increment ]`. I'm seeing `...` in the debugger.

![image](https://user-images.githubusercontent.com/2568148/47811195-874c1080-dd88-11e8-8cea-63c9d38a9c9b.png)
