### ISSUE TITLE
Integer division overflows with numbers around 2^41

### ISSUE THREAD

**Issue by malaire** [elm/compiler#1832]
Since there is already a bug #1246 about large `Int` literals, I use here a code example which doesn't use literals.

When calculating average of two `Time.Posix` values (which are around current time) with following code, the result is negative which is impossible. Only reason I can think of why this happens is an integer overflow.

    (Time.posixToMillis timeA + Time.posixToMillis timeB) // 2

But these values are around `2^41` while [documentation](https://package.elm-lang.org/packages/elm/core/latest/Basics) says that `Int` is safe up to `2^53-1`.

Elm: 0.19
OS: Debian Stretch
Browser: Firefox 60.2.2.esr

Ellie: https://ellie-app.com/3GMzMd67KPBa1

SSCCE:
```
module Main exposing (main)

import Browser
import Html exposing (div, text)
import Task
import Time


main =
    Browser.element
        { init = init
        , update = update
        , subscriptions = \_ -> Sub.none
        , view = view
        }


type Msg
    = NewTime Time.Posix


init : () -> ( Int, Cmd Msg )
init _ =
    ( 0
    , Task.perform NewTime Time.now
    )


update msg model =
    case msg of
        NewTime time ->
            ( (Time.posixToMillis time + Time.posixToMillis time) // 2, Cmd.none )


view model =
    div [] [ text (String.fromInt model) ]
```

**Comment by billstclair** [comment]
The problem appears to be that the following Elm:

    i = 3080440570266 / 2

Compiles into the following JavaScript:

    var user$package$module$i = (3080440570266 / 2) | 0;

The `| 0` operation truncates to 32 bits.

JavaScript integers go up to `Number.MAX_SAFE_INTEGER`, which is 9007199254740991, 2^53-1

**Comment by evancz** [comment]
I have added some bold to the documentation you mention:

> `Int` math is well-defined in the range `-2^31` to `2^31 - 1`. Outside of that range, the behavior is determined by the compilation target. When generating JavaScript, the safe range expands to `-2^53` to `2^53 - 1` **for some operations**

There are a bunch of tradeoffs about performance and sensibility because the compilation target is quite odd. I don't think there is a set of changes that everyone will agree is correct, so I'd rather not mess with the balance of things at this time.

**Comment by rue** [comment]
Old issue, but given the tradeoffs etc, would it make sense to just add constants for the max available values to use for bounds checking?

**Comment by coinop-logan** [comment]
So wait, is this solved? I'm still seeing some negative results of // division:

```        timeInt =
            Time.posixToMillis t

        truncatedTime =
            timeInt // 100
```

truncatedTime ends up negative...

I'm kind of shocked at this behavior. Dividing two positives should never output a negative in a typesafe language. I guess now I need to roll my own "safe division" method and handle a bunch of Maybes? Or wait for someone else to do it?

**Comment by malaire** [comment]
This was "solved" by defining -2^31 to 2^31 - 1 as safe range for `Int` math operations. `Time.posixToMillis` returns larger values, so math operations on those values are not safe.
