### ISSUE TITLE
Proposal: port subscription lifecycle events 

### ISSUE THREAD

**Issue by jhillyerd** [elm/compiler#1844]
It would be helpful for JavaScript code to know if the Elm app is currently subscribed to the messages it's sending.  The JS code could then free up resources, stop timers, or close web sockets when they are not needed.

In my particular case, I have a single page that listens to a websocket via an inbound port.  I had to add some logic to my router to send a close message when it sees the user transition away from that page, which did not feel very elegant.

**Comment by evancz** [comment]
We try to keep issues just about specific bugs. We tend to discuss feature suggestions on discourse. Maybe try to get other people to share other concrete examples of cases where they think this would be helpful.
