### ISSUE TITLE
Map.! error when using a dependency which has a type alias to a non-exported module

### ISSUE THREAD

**Issue by mbark** [elm/compiler#1852]
# Map.! error with --debug when using a dependency which has a type alias to a non-exported module
This is an example the error described in #1851, in this case because one of the messages has a type alias which points to some external dependencies type, which in turn is just a type alias for something in a non-exported module.

- **OS**: macOS Mojave
- **Elm:** 0.19.0
- **SSCCE**: See this [repo](https://github.com/mbark/elm-debug-error-ssscce) for a simple example of when this happens.

## Description

Running `elm make  src/Main.elm --debug` in the [SSCCE repo](https://github.com/mbark/elm-debug-error-ssscce) fails:
```
$ elm make src/Main.elm --debug                                                                                                                          [I] Wed Nov 21 10:38:22 2018
Success! Compiled 1 module.
elm: Map.!: given key is not an element in the map
CallStack (from HasCallStack):
  error, called at libraries/containers/Data/Map/Internal.hs:603:17 in containers-0.5.10.2:Data.Map.Internal
```

This is we have a message using the type `Point` (from [Bractlet/elm-plot](https://github.com/Bractlet/elm-plot)):
```
import Plot exposing (Point)

type Msg
    = Msg Point
```

`Point` is exported from `Bractlet/elm-plot` but is there just a type alias for `Draw.Point` where `Draw` is an internal module that is not included in the `exposed-modules` in the package's `elm.json`.

In my SSCCE I have also included the commands to move the `elm-plot` source into your own code -- which will make `--debug` work.

## Workaround

A simple workaround for this problem is to make your own type alias instead of using the one that causes the breakage.

In our case `Point` is `Draw.Point` is `{ x : Float, y : Float }` so we create our type alias and use that, i.e.:

```elm
type alias PlotPoint =
    { x: Float, y: Float}
```

**Comment by evancz** [comment]
The root issue is resolved in the development version of the compiler. I described it in a bit of detail [here](https://github.com/elm/compiler/pull/1850#issuecomment-509327575).

The fix should come out with the upcoming 0.19.1 release. Thank you for the report!
