### ISSUE TITLE
CORRUPT DEPENDENCY while building elm/core Ubuntu Linux i386

### ISSUE THREAD

**Issue by movefasta** [elm/compiler#1854]
Hello
Got an issue while building elm/core package:
```
$ elm make
Starting downloads...

  ● elm/time 1.0.0
  ● elm/url 1.0.0
  ● elm/virtual-dom 1.0.0
  ● elm/browser 1.0.0
  ● elm/json 1.0.0
  ● elm/html 1.0.0
  ● elm/core 1.0.2

Dependencies ready!                
-- CORRUPT DEPENDENCY ----------------------------------------------------------

I ran into a problem while building the following package:

    elm/core 1.0.2

This probably means the downloaded files got corrupted somehow. Try deleting
/home/brylev/.elm (a directory for caching build artifacts) and see if that
resolves the issue.
```
**OS**: Ubuntu 14.04.5 LTS
**Kernel**: Linux 3.13.0-161-generic (i686)
**Elm Version**: 0.19
Elm executables compiled from sources using GHC 8.2.2 without elm reactor ([issue](https://github.com/elm/compiler/issues/1750) and [source code patch](https://files.slack.com/files-pri/T0CJ5UNHK-FCDEAHAFN/removed_reactor__to_build_elm_0_19_on_openbsd_6_3_.txt) )

**Comment by evancz** [comment]
It sounds like you are using a custom build rather than the pre-built binaries. I cannot support errors that come from people modifying the source code in other ways, especially without an SSCCE. If there is some bug that needs to be fixed, that can make an issue.

**Comment by karldray** [comment]
@movefasta did you ever solve this? i'm running into the same thing trying to install elm on 32-bit linux.

**Comment by rlefevre** [comment]
There is an unofficial patch for 32bit support in Elm 0.19.1 here:
https://github.com/dmy/elm-raspberry-pi/blob/master/patches/elm-0.19.1.patch

There is an unofficial Debian 10 i386 version without support here:
https://gist.github.com/rlefevre/8fcf368d9951137e9e810c06c111bba1

Please do not report issues about those here.
