### ISSUE TITLE
elm 0.19 REPL error "elm: Map.!: given key is not an element in the map"

### ISSUE THREAD

**Issue by movefasta** [elm/compiler#1855]
Hello
got an error while using any elm repl command :
```
$ elm repl
---- Elm 0.19.0 ----------------------------------------------------------------
Say :help for help and :exit to exit! More at <https://elm-lang.org/0.19.0/repl>
--------------------------------------------------------------------------------
> 2
elm: Map.!: given key is not an element in the map
CallStack (from HasCallStack):
  error, called at libraries/containers/Data/Map/Internal.hs:603:17 in containers-0.5.10.2:Data.Map.Internal
CallStack (from -prof):
  Data.Map.Internal.CAF (<entire-module>)
```
**OS**: Ubuntu 14.04.5 LTS
**Kernel**: Linux 3.13.0-161-generic (i686)
**Elm Version**: 0.19
Elm executables compiled from sources using GHC 8.2.2 without elm reactor ([issue](https://github.com/elm/compiler/issues/1750) and [source code patch](https://files.slack.com/files-pri/T0CJ5UNHK-FCDEAHAFN/removed_reactor__to_build_elm_0_19_on_openbsd_6_3_.txt) )

**Comment by movefasta** [comment]
It's another **elm: map!** issue to Evan's [collection](https://github.com/elm/compiler/issues/1851)

**Comment by evancz** [comment]
It doesn't 100% make sense why this would trigger the `--debug` issue. That said, I am not able to reproduce this with the development version.

Some information about the `--debug` fix is available [here](https://github.com/elm/compiler/pull/1850#issuecomment-509327575), and it seems like whatever was going on here will be resolved as well.
