### ISSUE TITLE
5 SSCCEs for Map.! error 

### ISSUE THREAD

**Issue by jinjor** [elm/compiler#1864]
I created 5 SSCCEs for Map.! error.
Most of them are already reported, but I was able to make them much shorter.

1. Array
```elm
-- Always fails
main : Program () () (Array ())
main =
    Debug.todo ""
```

2. Html
```elm
-- Fails if elm/virtual-dom is in "indirect"
main : Program () () (Html ()) -- or Attribute
main =
    Debug.todo ""
```

3. Svg
```elm
-- Fails if elm/virtual-dom is in "indirect"
main : Program () () (Svg ())  -- or Attribute
main =
    Debug.todo ""
```

4. Plot from Bractlet/elm-plot (#1852)
```elm
-- Bractlet/elm-plot
-- Point is an alias of a type in non-exposed Module
import Plot exposing (Point)

type Msg
    = Msg Point

-- Fails
main : Program () () Msg
main =
    Debug.todo ""
```

```elm
-- Succeeds
main : Program () () Point
main =
    Debug.todo ""
```

5. Part from jinjor/elm-req
```elm
-- jinjor/elm-req
-- Part contains File and Bytes
import Req exposing (Part)

-- Fails if elm/file or elm/bytes is in "indirect"
main : Program () () Part
main =
    Debug.todo ""
```

From those examples, it should be true that **Msg cannot be / contain a type from non-exposed module**.

Details can be seen here.
https://github.com/jinjor/elm-map-sscce

**Comment by jinjor** [comment]
I just published a package for testing various patterns.
https://package.elm-lang.org/packages/jinjor/elm-map-debug/latest

Results:
https://github.com/jinjor/elm-map-sscce/tree/master/tests

**Comment by evancz** [comment]
Thank you for organizing this!

I just went through with the development build of the compiler, and all of the files in `src/` directories compile successfully now. Some additional details on the fix are available here: https://github.com/elm/compiler/pull/1850#issuecomment-509327575

Thanks again for getting the examples down so small and making it really easy to test them!
