### ISSUE TITLE
Relative file paths inconsistent between `elm make` and `elm reactor`

### ISSUE THREAD

**Issue by stevensonmt** [elm/compiler#1867]
I have some image here `myApp/src/images/myImage.png`. My `Main.elm` lives in `myApp/src/`. When I run `elm reactor` the path to the image must be `"images/myImage.png"`. But when I run `elm make src/Main.elm` the resulting `index.html` expects the path to be `"src/images/myImage.png"`. Of course moving `index.html` into the `src` folder resolves the path correctly, but I cannot really run the app that way. This limits utility of `reactor` significantly.

Elm 0.19, Manjaro Linux, chromium browser

**Comment by ampheul** [comment]
I agree, this is annoying. What should the fix be though? We know what's causing it is the different root path for each url.

**Comment by evancz** [comment]
If you run `elm reactor` in the `myApp/` directory, it will serve a file named `myApp/*` at `http://localhost:8000/*`

If you run `elm reactor in the `myApp/src/` directory, it will serve a file named `myApp/src/*` at `http://localhost:8000/*`

I recommend running `elm reactor` from `myApp/` and then navigating to `src/Main.elm` from _within_ the reactor. This will compile the file, and I think the paths will work as you expect.
