### ISSUE TITLE
[Linux] elm package fetching HTTP request failing

### ISSUE THREAD

**Issue by atlemagnussen** [elm/compiler#1870]
OS: Arch Linux
elm 0.19.0 installed via NPM
also tried downloading binaries with the same result

Can't install any packages, so already on `elm init` this happens:
```sh
$ elm init
Hello! Elm projects always start with an elm.json file. I can create them!

Now you may be wondering, what will be in this file? How do I add Elm files to
my project? How do I see it in the browser? How will my code grow? Do I need
more directories? What about tests? Etc.

Check out <https://elm-lang.org/0.19.0/init> for all the answers!

Knowing all that, would you like me to create an elm.json file now? [Y/n]: y
-- HTTP PROBLEM ----------------------------------------------------------------
The following HTTP request failed:

    <https://package.elm-lang.org/all-packages>

Here is the error message I was able to extract:

    HttpExceptionRequest Request { host = "package.elm-lang.org" port = 443
    secure = True requestHeaders =
    [("User-Agent","elm/0.19.0"),("Accept-Encoding","gzip")] path =
    "/all-packages" queryString = "" method = "GET" proxy = Nothing rawBody =
    False redirectCount = 10 responseTimeout = ResponseTimeoutDefault
    requestVersion = HTTP/1.1 } (ConnectionFailure Network.Socket.getAddrInfo
    (called with preferred socket type/protocol: AddrInfo {addrFlags =
    [AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream,
    addrProtocol = 6, addrAddress = <assumed to be undefined>, addrCanonName =
    <assumed to be undefined>}, host name: Just "package.elm-lang.org", service
    name: Just "443"): does not exist (Try again))
```
- I have disabled ipv6 completely on my computer, since the error message says addrProtocol=6. I have no ipv6 addresses on any interfaces

- https://package.elm-lang.org/all-packages works fine in my browser, wget and curl, even with the same headers provided as in the error message.
```sh
$ curl https://package.elm-lang.org/all-packages
{"1602/elm-feather":["1.0.0","1.0.1","1.0.2","2.0.0","2.0.1","2.1.0","2.2.0","2.3.0","2.3.1","2.3.2","2.3.3","2.3.4"],"1602/json-schema":["1.0.0","1.1.0","2.0.0","3.0.0","4.0.0","4.1.0","4.1.1"],"1602/json-value":["1.0.0","1.1.0","2.0....
```

**Comment by prog-re** [comment]
Did you solve this? I have the same problem. I can sort of make it work by pinging the domain names (package.elm-lang.org and github.com) and adding the IP:s to /etc/hosts. This seems fragile though, so I would much rather have a real solution

**Comment by atlemagnussen** [comment]
@prog-re No still having the same issue. Will try your temp fix, thanks

**Comment by birdspider** [comment]
I have the same issue, curl and node.js work though

curl

    curl -v -H "User-Agent: elm/0.19.0" -H "Accept-Encoding: gzip" \
      'https://package.elm-lang.org/all-packages' | gunzip

pure node.js

    const http = require("https"); 
    http.get('https://package.elm-lang.org/all-packages',(resp) => {
      let d = ''; 
      resp.on('data', c => d += c); 
      resp.on('end',() => console.log(d)) 
    });

both end correctly with the requested data:

    // the requested json ends with 
    ... zwilias/json-decode-exploration":["1.0.0","2.0.0","3.0.0","4.0.0","4.1.0","4.1.1",
    "4.1.2","4.2.0","4.2.1","4.3.0", "5.0.0","5.0.1"],
    "zwilias/json-encode-exploration":["1.0.0"]}

**Comment by evancz** [comment]
@prog-re, are you on Arch Linux as well? How did you install Elm?

@birdspider, did you install Elm with the `npm` installer as well?

**Comment by birdspider** [comment]
@evancz I'm pretty sure that either my DNS setup was wrong or at that time `package.elm-lang.org` was not resolvable via ip6-dns

```
✔ 15:56 ~ $ getent ahostsv4 package.elm-lang.org
159.89.227.162  STREAM package.elm-lang.org
159.89.227.162  DGRAM
159.89.227.162  RAW

✔ 15:56 ~ $ getent ahostsv6 package.elm-lang.org
::ffff:159.89.227.162 STREAM package.elm-lang.org
::ffff:159.89.227.162 DGRAM
::ffff:159.89.227.162 RAW
```

this is now, but AFAIK the second command did not return anything back then

**Comment by evancz** [comment]
Okay, it seems like the root issue folks are seeing here is coming from system configuration.

It may be that some DNS does not know about `package.elm-lang.org` or something. I have heard there are issues in Russia because that IP address is on the same block as the Telegram messenger servers, and they just blocked a whole range of addresses there. Sounds like some less serious problem for the posters here.

If someone can pin this down to a particular action that can be taken by the package website, please create a new issue!
