### ISSUE TITLE
Different Versions of same package are not allowed for dependencies

### ISSUE THREAD

**Issue by ChristophP** [elm/compiler#1871]
**What's the problem?**
I am the author of a [package](https://package.elm-lang.org/packages/ChristophP/elm-i18next/4.0.0/) for translations, which used to have a dependency on `elm/http`. Consider this scenario where an an application uses both `elm/http` and `Christoph/elm-i18next` so that the dependency tree looks like this:

```
# elm/http is both a direct and an indirect dependency
app
|- elm/http   
|- ChristophP/elm-i18next
    |- elm/http
```

As a `package author` I need to make a decision which (major) version of `elm/http` to use.
- If I pick v1, then users who use `elm/http` v2 in their project cannot use my lib.
- If I pick v2, then users who use `elm/http` v1 will either have to upgrade their app to use v2 as well or not receive updates of my lib anymore.

As an `application author` I need to decide the following (considering the http version is different):
- Either I need to update my app to use the same version of `elm/http` that my lib is using
- or I do not use that lib.

**Worst case**
If two packages depend on different (major) versions of `elm/http` they cannot be used together in any project.

**Why is this coming up now?**
With the recent breaking change for `elm/http` from 1 to 2 many packages needed updating.

**How did I solve the issue?**
Luckily `elm/http` was only needed for a non-essential function in my package so I was able to remove that dependency, allowing users to pick their version of `elm/http` freely. However, not every package author will have that option.

**Suggestion**
It would be great if dependecies of dependencies are kind of `sandboxed`, so that users don't have to worry about ranges so much, so that "it shouldn't matter which versions my dependencies are using".
I am not advocating NPM as a great package manager, but the way NPM handles this situation is pretty comfortable for the users as dependecies of dependecies can bring their own versions, giving users the freedom to choose versions independently of the ones used in their direct dependencies.

**Comment by ChristophP** [comment]
I think the output of `npm ls chalk` says best what I mean.
![image](https://user-images.githubusercontent.com/5880236/50546571-01ceca80-0c2a-11e9-8850-e802cb59c353.png)
I every dependency gets the version of `chalk` that satisfies its constraints. While deduping if the versions are compatible.

**Comment by evancz** [comment]
This was one of the design options considered when the package system was first designed.

It has many significant downsides:

1. Code size can get out of hand easily. Part of why we can get [much smaller assets](https://elm-lang.org/blog/small-assets-without-the-headache) is that we don't have N versions of the same package.
2. When you have a type system, you have questions like "is `List@1.0.0` equal to `List@1.0.1`?" Probably? Maybe they are actually structurally different between patch changes. So the fact that you let things "just be fine" with different dependencies means that you can commit really heavily to packages with clashing transitive dependencies, only finding out that they are incompatible in important ways at a much later time, when you happen to want to pass a `List` between functions from different packages.

Problem (2) is one of the most frustrating things I can imagine from a package system. Imagine folks constantly running into `Dict@1.0.0` is not equal to `Dict@1.1.0`. "What? Why are there even different dictionaries in my code?"

Given the information I have now, this is not a change that I plan to make. The motivating example has a work around, and the "fix" for that scenario causes very very serious downsides in other cases.
