### ISSUE TITLE
Proposal: Functions - Automatic Parameters

### ISSUE THREAD

**Issue by AlmightyFloppyFish** [elm/compiler#1873]
### Problem
Let's say we have this code
```elm
header : String -> Html msg
header t = h1 [] [ text t ]

view m =
    div []
        [ header "Welcome"
        , subheader "1"
        , text ""
        , subheader "2"
        , text ""
        ]
```
But then we want to add both a dark and light theme to the website, being changeable during runtime. This would require us to add parameters to `header` and `subheader` so the functions can know which colour to select (assuming their colours are different in light/dark mode + different than other text) which will create very verbose and ugly code
like so
```elm
type Theme = Light | Dark

model =
    { theme = Light
    }

header : String -> Theme -> Html msg
header t theme =
    h1
        [ if theme == Light then
            style "color" "#000000"
          else
            style "color" "#111111"
        ]
        [ text t ]

view model =
    div []
        [ header "Welcome" model.theme
        , subheader "1" model.theme
        , text ""
        , subheader "2" model.theme
        , text ""
        ]
```
This gets worse and worse when you add more layers of functions, where a function that doesn't look like it'd need `model.theme`, needs it because it uses `header` somewhere inside.

### Idea
I suggest we add a new form of parameter that will automatically take in a parameter based on it's name. In this case we'd turn 

```elm
header : String -> Theme -> Html msg
header t theme =
```
into
```elm
header : String -> {model.theme} -> Html msg
header t theme =
```
Resulting in it implicitly getting the `theme : Theme`  parameter. Allowing us to change the code into something like:

```elm
type Theme = Light | Dark

model =
    { theme = Light
    }

header : String -> {model.theme} -> Html msg
header t theme =
    h1
        [ if theme == Light then
            style "color" "#000000"
          else
            style "color" "#111111"
        ]
        [ text t ]

view model =
    div []
        [ header "Welcome"
        , subheader "1"
        , text ""
        , subheader "2" 
        , text ""
        ]
```
Allowing our view function to remain easily read even with this extra layer of complexity.

Opinions?

**Comment by miniBill** [comment]
This is not the correct place for RFCs, you should post your idea in the Discourse forum.
I think it will be rejected, anyway, because having funtion signatures get more complex for more parameters is good, it forces you to rethink your strategy before your complexity gets out of hand. Plus, it would make refactoring harder, and that's Bad.

In your case I'd suggest simply accepting that if some part of your view needs access to the current theme, then their parents do too, and so on. You can always use records to cut down the number of arguments anyway.

**Comment by AlmightyFloppyFish** [comment]
I'll reconsider and if still thinking it's a good idea, put it forward elsewhere.
