### ISSUE TITLE
`onClickPreventDefault` produces consistent and erratic runtime errors

### ISSUE THREAD

**Issue by francescortiz** [elm/compiler#1874]
First of all, I want to apologize because I couldn't come with a SSCCE. I cannot share my whole project, and when I simplify the code the error stops ocurring.

In short: I believe that using `onClickPreventDefault` from elm-community/html-extra causes the compiler to produce errors. The errors are always the same. The runtime is trying to read `elmFs` or `value` from something that is undefined.

The reason why I say it is erratic is because before I realized that it was `onClickPreventDefault` I could fix the error by removing or rearranging html nodes.

**Triggering the error:**
Even though the error would start at a random point, triggering the error was very consistent. I had a button in a submodule that triggered a port. Then, the port would trigger a subscription after one second. The response to the subscription then would replace the subcomponent with another one. At this point the error would start to happen in an infinite `requestAnimationFrame` loop even though I don't have anything related to animations.

I tried delaying one second the subcomponent replacement and it didn't help. As soon as I would replace the subcomponent the error would start to spawn.

Blaming the way prevent default is handled by the runtime might not be correct, I might have just pushed the problem farther, but I don't have enough knowledge on how the runtime works to come with another conclusion.

I spent some hours trying to understand what was going on. If there is something else I could have done, please, tell me.

PS: Also, I realized that I had two elm `Browser.application` instances launched at the same time. This can also be the cause of the problem, but I don't know the runtime works. Removing the second instance allows me to put back `onClickPreventDefault`.

**Comment by SidneyNemzer** [comment]
Two Elm programs using `Browser.application` on the same page could very likely cause the issue you're seeing. The problem is that one of the Elm programs gets confused when the DOM has been modified -- or rather, it does not expect it at all, so it tries to access elements that don't exist. The runtime uses `requestAnimationFrame`  for rendering view updates.

I would recommend only using one program. You may be able to merge the programs into one.

**Comment by francescortiz** [comment]
Launching two elm programs is a mistake I made when integrating templates with js using webpack I was supposed to launch just one program. Also, I am totally aware that I cannot modify the dom externally to elm. It keeps the virtual dom state and it never checks, just applies. I keep the issue because:

- I would have expected the runtime to detect that another instance is already taking control of the page and show a warning at least, the same way the compiler is superhelpful, I would have expected that.
- I don't know anything of how the runtime works, so I am not the one to decide whether this is minor because of my mistake or if it is something else that just raised in this scenerario but that shouldn't happen anyway.

**Comment by evancz** [comment]
It sounds like the root issue is that there are no warnings or messages when two `Browser.application` instances are started on the same page. I don't think adding such detection would be super high priority, but it's worth making a note on `elm/browser` with title "Should there be an explicit warning or error when running two Browser.application instances?"
