### ISSUE TITLE
Elm 0.19.0 on Windows 7 32-bit

### ISSUE THREAD

**Issue by roman2git** [elm/compiler#1878]
Hello,  

I'm trying to install Elm 0.19.0 on Windows machine: 
Windows7 Enterprise SP1, 32-bit OS.  

Tried installation variants: 
* with [windows installer](https://github.com/elm/compiler/releases/download/0.19.0/installer-for-windows.exe), 
* directly [downloading tar.gz](https://github.com/elm/compiler/releases/download/0.19.0/binaries-for-windows.tar.gz).  

Both variants return the same error:
```
c:\>where elm
C:\Program Files\Elm\0.19\bin\elm.exe

c:\>elm --help
This version of C:\Program Files\Elm\0.19\bin\elm.exe is not compatible with the version of Windows you're running. Check your computer's system information to
see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

c:\APPS\try_elm>elm --help
This version of c:\APPS\try_elm\elm.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether yo
u need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.
```

I also tied variant with npm but that doesn't work (node is installed into custom place so maybe that is the reason) but anyway when I tried to run `c:\APPS\node\node_modules\elm\unpacked_bin\elm.exe --help`
I got the same error. 

Unfortunately I didn't found any info about supported OS or OS requirements,   
**So the question**: is the w32 platform supported and if yes - how to get it works? 

Thank you.

**Comment by pwrsoft** [comment]
The same issue here - can't use elm on my win32 home pc workstation.
Could someone advice?

**Comment by roman2git** [comment]
I tried to compile from the source and I can share my experience (I should notice - that was my first experience with Haskell). As it was 3 month ago - I'm not sure everything still valid. 
1. Stack doesn't work on Win32, so the right way is to go with cabal. 
2. Requirements in elm.cabal would expect ghc-8.2.2 (lts-11-20) which has a bug for Win32. That bug was fixed in later versions. 

After several tries I stop with ghc-8.6.3. Beside that I wasn't able to make elm.cabal dependencies in right way so I just remove all version from "Build-depends" section in elm.cabal (except of couple because their newer had some bugs). Also there was some package which had solved bug but not published - so that one was installed manually (even not installed - I replaced the package which came from Cabal with fixed from GitHub). 
After all (and tonne of spent time) I was able to pass about all steps in compilation plan. The last issue came when compilation required Elm packages (those steps are at the end of build process). That issue I wasn't able to solve and gave-up there.

Unfortunately I don't have that Win32 machine anymore and everything was done there is lost so I can't give more detail to make this comment helpful.
In general - I think it's possible to compile the Elm for win32 but that requires good experience with Haskell compilations and Elm project.

PS: and yes - third part of time was spent just to make ghc + cabal work in Win, that is painful enough. I do not know if Haskell allows cross-platform compiling but if so - it would be easier to fire-up VM with Linux 32bit and compile it there.

**Comment by evancz** [comment]
We are currently only building 64-bit binaries, so that is what is available through the installer and through `npm`.

I made some notes about building from source in https://github.com/elm/compiler/issues/1949, and it looks like @roman2git ran into the typical woes of trying to build things with Haskell using older versions. Lots of things can go wrong just with the package dependencies.

We do not have plans to start distributing 32-bit binaries, so I am going to close, but I am interested to get an idea of the number of people who may need to use 32-bit versions for some reason. Perhaps it is a larger group than I know about, so I am interested in why this is necessary in your particular case / what your case is exactly.

**Comment by roman2git** [comment]
> 
> We do not have plans to start distributing 32-bit binaries, so I am going to close, but I am interested to get an idea of the number of people who may need to use 32-bit versions for some reason. Perhaps it is a larger group than I know about, so I am interested in why this is necessary in your particular case / what your case is exactly.

Hi @evancz , 
thank you for the answer.

I was pushed to use/look for 32-bit version just because I had had 32-bit machine at work (yes - that still may happen). 

PS: I 'd like to note that there is no one place with any info about system requirements for Elm binary distribution usage. That is 'nice to have feature' however may save someone's time.

**Comment by pwrsoft** [comment]
I'm using 32-bit Windows PC too. So it would be very helpful to see 32-bit version of elm compiler.
Thanks!

**Comment by tellts** [comment]
Hello. In Windows XP 32 bits does not work. And bad link https://guide.elm-lang.org/install.html.
