### ISSUE TITLE
elm install - UnsafePath error on install from zipball

### ISSUE THREAD

**Issue by tzemanovic** [elm/compiler#1882]
Hi,

Elm version 0.19.0, macOS 10.13.6.

Command `elm install 1602/elm-feather` was failing with:

```bash
 -- HTTP PROBLEM ----------------------------------------------------------------

The following HTTP request failed:

    <https://github.com/1602/elm-feather/zipball/2.3.4/>

Here is the error message I was able to extract:

    UnsafePath "/Users/tzemanovic/.elm/0.19.0/package/1602/elm-feather/2.3.4/"
```

I found that the condition in zip-archive for this is:
```haskell
let isUnsafePath = ".." `isInfixOf` absPath ||
                     not (curDir `isPrefixOf` absPath)
```

From there I found a work-around to `elm init` and `elm install` this package in `~/.elm/0.19.0` directory, which indeed worked and then I was able to install it elsewhere thanks to cache.

**Comment by jerith666** [comment]
Thanks for tracking that down!  Further details: that was added in https://github.com/jgm/zip-archive/issues/50.

I'm curious if you obtained your `elm` binary through the standard `npm install` mechanism, or if you built it yourself somehow.

I'm seeing this in the [elm that's packaged](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/compilers/elm) in [nixpkgs](https://github.com/NixOS/nixpkgs/), after the latter's update from GHC 8.4 to 8.6 and accompanying hackage updates (https://github.com/NixOS/nixpkgs/commit/91ec96d77d146efa7595b6d3f12193a89958ec0a and https://github.com/NixOS/nixpkgs/commit/11312448890631c90b793cce60765be9a65049ed).

**Comment by tzemanovic** [comment]
Hi, thanks for checking this! I was using elm installed via nixpkgs, so that explains it.

**Comment by jerith666** [comment]
Okay, so I think we should probably leave this issue open as a heads-up for the core Elm team when they decide to update to `zip-archive` 0.4.  But also open an issue against nixpkgs ... the answer over there may just be to build against `zip-archive < 0.4` for now.

**Comment by jerith666** [comment]
Sorry, one more piece of info here: I think the core problem is that the `Deps.Website.writeArchive` function [here](https://github.com/elm/compiler/blob/master/builder/src/Deps/Website.hs#L245) is trying to write out each entry of a zip file it has downloaded into a specific *absolute* target directory (under `~/.elm/` typically).  But the fix to jgm/zip-archive#50 means `writeEntry` is no longer suitable for this.

Probably we can just use `fromArchive :: Archive -> ByteString` and `writeFile :: FilePath -> ByteString -> IO ()` instead?

**Comment by eikek** [comment]
Hi @tzemanovic I just ran into this and can't figure out which workaround you found out? I'm on nixos and can't seem to install any elm package (`elm init && elm make` fails). Could you share more about this workaround? Thanks!

**Comment by eikek** [comment]
@jerith666 thanks a lot for the fix! Don't worry about any delay…

**Comment by evancz** [comment]
This should only manifest in binaries that were built by 3rd parties. Using the binaries from https://github.com/elm/compiler/releases/tag/0.19.0 should not have this problem.

Separately, the development version has stopped relying on the function in `zip-archive` that got the extra `..` check. This is described in more detail here: https://github.com/elm/compiler/pull/1886#issuecomment-509324011

So the root problem should not manifest in official builds of 0.19.1 either once that is released.
