### ISSUE TITLE
Confusing type error when using Dict.filter.

### ISSUE THREAD

**Issue by rupertlssmith** [elm/compiler#1898]
I called `Dict.filter` with a `String -> Bool` function as the filter, not realising that it actually needs a `String -> a -> Bool` function. The resulting error message is a bit weird:

```
The 1st argument to `filter` is not what I expect:

31|     Dict.filter match d
                    ^^^^^
This `match` value is a:

    String -> Bool

But `filter` needs the 1st argument to be:

    String -> Bool
Detected errors in 1 module.       
```

I would expect the error message to say

```
But `filter` needs the 1st argument to be:

    String -> a -> Bool
```

## SSCCE

```
import Dict exposing (Dict)

test : (String -> Bool) -> Dict String a -> Dict String a
test match d =
    Dict.filter match d

```

- **Elm:** 0.19
- **Browser:** Chrome, but this error is during compilation.
- **Operating System:** Linux 4.9.0-4-amd64 Debian

**Comment by evancz** [comment]
Thank you for the nice report and SSCCE! The new error should be like this, with both types fully highlighted in yellow.

```
-- TYPE MISMATCH ------------------------------------------------------ temp.elm

The 1st argument to `filter` is not what I expect:

5|     Dict.filter match d
                   ^^^^^
This `match` value is a:

    String -> Bool

But `filter` needs the 1st argument to be:

    String -> v -> Bool

Hint: It looks like it takes too few arguments. I was expecting 1 more.
```

There was some code that tried to highlight the arguments that were not in common that was messing up. More details on that in https://github.com/elm/compiler/commit/a5febad184588ae79b404d22a020020408580041
