### ISSUE TITLE
Equality parse error inside repl when result is true

### ISSUE THREAD

**Issue by mainlymortal** [elm/compiler#1902]
**Quick Summary:** I'm just starting with elm so feel free to let me know how wrong I am but for some reason I can't do a simple equality comparison of two values in the command line repl.

## SSCCE

```elm
> 1 == 1
-- PARSE ERROR ------------------------------------------------------------- elm

Something went wrong while parsing your code.

3| 1 == 1
   ^
I was expecting:

  - a declaration, like `x = 5` or `type alias Model = { ... }`
  - the `import` keyword
  - a doc comment, like {-| this -}
```

- **Elm:** 0.19.0
- **Browser:** N/A
- **Operating System:** MacOS Mojave

## Additional Details

As the summary above mentions I can't compare any two values for equality in the repl. This goes for all types like strings, chars, lists e.t.c

I can however check if two values are not equal which produces the result I was expecting.

```elm
> 1 /= 1
False : Bool
```

I can also get the correct result by wrapping the expression in parens.

```elm
> (1 == 1)
True : Bool
```

Is this just a quirk of the repl or is it possibly a bug?

**Comment by rlefevre** [comment]
Yes this is a known bug with `elm repl`.

See https://github.com/elm/compiler/issues/1736 
or https://github.com/elm/compiler/issues/1787.

**Comment by mainlymortal** [comment]
Well I feel stupid. I looked but obviously not hard enough. Thank you for the follow up.
