### ISSUE TITLE
elm install freeze

### ISSUE THREAD

**Issue by yousefvand** [elm/compiler#1917]
**elm install freeze and high CPU** 

Using following bash script I have tried to install all Elm packages in a project but after about 50 packages are installed, installation process stops and `elm` cpu usage is over 99% without progress.

```bash                                              

#!/usr/bin/env bash

packages=`curl -s https://package.elm-lang.org/search.json | jq -r '.[].name'`

for item in ${packages[@]}; do
  echo Y | elm install "$item"
done
```

- **Elm: 0.19.0**
- **Browser: none**
- **Operating System: Ubuntu 18.04.2 LTS**

## Additional Details

Also I get the following error message:

```
-- CORRUPT JSON ----------------------------------------------------------------

The elm.json for tesk9/accessible-html-with-css 1.0.1 got corrupted somehow.

I removed it from my file cache, so if it was some transient error it should be
fixed if you try the same thing again. Please report this if it seems like an
Elm problem though!
```

**Comment by evancz** [comment]
I do not understand the goal of this script. I also suspect that it is not possible to install all the packages that exist at once because they are unlikely to all have constraints that match.

So I suspect the high CPU may be that it is expensive to exhaustively search all the different constraints that exist once you hit a package that can never fit with the others. That means downloading a ton of things from the servers (not ideal at all!) and then exploring an extremely large search space locally.

Given the information available, I think this is the best explanation I can give at this time. If you can reproduce this sort of thing in a way that is clearly reproducible (simple steps that cause an error every time) you are welcome to open a new issue about that!

**Comment by evancz** [comment]
It may also be worthwhile to ask around on https://discourse.elm-lang.org/ or http://elmlang.herokuapp.com/ to get help with your particular goals. At this time it is hard to tell if it is a bug in the compiler, and the folks there can help!

**Comment by yousefvand** [comment]
The goal of the script is to have all documentations in `.cache` folder and extract them for using in a vscode Elm extension. At the time there is no general tool for extension developers to pass a keyword and get information about that ([elm-oracle](https://github.com/ElmCast/elm-oracle) is obsolete) and for code analysis, [elm-analyse doesn't work in offline mode](https://github.com/stil4m/elm-analyse/issues/196). There is a [good extension](https://github.com/halohalospecial/atom-elmjutsu) for Elm in Atom IDE but [the good one for vscode](https://github.com/yousefvand/vscode-elm-extension) had no progress after 0.19.0 release (probably because of elm-oracle). So the original problem is: there is no extension for vscode to program Elm in offline mode as good as the Atom one, so I'm moving to Atom just because of this, while vscode is superior IMO.

**Comment by Razzeee** [comment]
Funfact currently the intelliJ implementation is king.
I'm working on something for vscode (or in fact all IDEs) - but it's done when it's done.

There is this repo that should have all docs 
https://github.com/drathier/elm-offline

And https://github.com/dmy/elm-doc-preview to view it

Not sure if it is like you imagined, but I thought it might be nice to mention it.

**Comment by evancz** [comment]
It is possible to download the `docs.json` files directly from links like [this](https://package.elm-lang.org/packages/elm/core/1.0.2/docs.json), though I would ask that whatever tool you make does not have everyone download everything.

It'd be better to have it go through servers you run, so the server costs of the design are not passed along. You can also have folks download only as needed from your servers, to reduce the load even more.
