### ISSUE TITLE
Compiling `master` fails with missing file `Reporting/Problem`

### ISSUE THREAD

**Issue by rotty** [elm/compiler#1924]
Trying to build current master (commit 51e20357) fails with the following error message:

```
Resolving dependencies...
Configuring elm-0.19.1...
Preprocessing executable 'elm' for elm-0.19.1..
cabal: can't find source for Reporting/Problem in compiler/src, builder/src,
terminal/src, dist/build/elm/autogen, dist/build/global-autogen
```

This is using cabal 2.2.0.0 on a Debian buster amd64 installation.

**Comment by evancz** [comment]
I recommend compiling based on the 0.19.0 tag. There is ongoing work in master, so it is not always in a compiling state. If I do work on a separate branch, I get other comments saying that people cannot figure out where the work is happening. Whatever choice is made, it does not work well for everyone.

**Comment by rotty** [comment]
I see, thanks for the explanation. I find it strange, though, that people cannot figure out where work is happening, as `git log --graph` quite nicely orders most recent commits at the top, IIRC.
