### ISSUE TITLE
truthy `modBy a b == c` sometimes returns a Truthy non-True value.

### ISSUE THREAD

**Issue by michaelglass** [elm/compiler#1925]
**Quick Summary:**

`modBy a b == c` (and `modBy a b /= c`)  sometimes returns a Truthy non-`True` value.

## SSCCE
In elm repl (locally and http://elmrepl.cuberoot.in/)

```elm
> a = (modBy 4 5 /= 0)
1 : Bool
> (a == True)
1 : Bool
> (a == False)
False : Bool
```

Expected
```elm
> (modBy 4 5 /= 0)
True : Bool
```

- **Elm:** 0.19.0
- **Browser:** n/a
- **Operating System:** Mac OS 10.14.3 and http://elmrepl.cuberoot.in/

## Additional Details
The main reason this is a problem is elm tests fails to compare values correctly.

```
✗ leap year

    96
    ╷
    │ Expect.equal
    ╵
    True
```

**Comment by zwilias** [comment]
Hey @michaelglass!

This looks like it's due to `/= 0` being a bit too optimized (see #1810). The fix for this has been merged into `master` but hasn't been released yet.

Cheers!
