### ISSUE TITLE
Include version suffix in the `elm --version` output

### ISSUE THREAD

**Issue by ondrejsevcik** [elm/compiler#1929]
I've installed elm with installer, but also with npm (0.19.0-bugfix6) and now when I run `elm --version` it shows me just `0.19.0`. So I'm not 100% sure what version I'm running without further investigation. 

It would be great if the `elm --version` would show also the version suffix.

**Comment by zwilias** [comment]
The `-bugfix*` suffix pertains only to the npm installer itself, i.e. the exact version of the script used to download the Elm binaries. All 0.19.0 npm package versions install the exact same version of Elm under the hood. There are minor differences in how they actually do that, but the final result is the same.

To figure out whether you're using the binaries installed through npm of through the installer, you can have a look at your `PATH` variable to figure out which location has higher precedence.

**Comment by harrysarson** [comment]
If you installed elm with npm then 

```sh
$ npm ls -g elm
```

Will give you the version :)

**Comment by ondrejsevcik** [comment]
Thanks guys. I just thought that it would be nice to have a full version name behind `--version` as it is a common practice. But maybe this could be solved if the version patch number would be incremented instead, rather than adding suffix `bugfix`.

**Comment by harrysarson** [comment]
The elm executable is _exactly_ the same regardless of which revision of the npm installer is used. Changing the output of the `--version` flag would require recompiling all the elm binaries when none of the code in them changes.

**Comment by evancz** [comment]
I have talked to the folks managing the `npm` installer (which is the source of the suffix, not the binary or compiler itself) and I am hopeful that the confusion about what this suffix means will be resolved in future releases.
