### ISSUE TITLE
Optimized JS can produce TypeError: rr is not a function. (In 'rr(n)', 'rr' is undefined)

### ISSUE THREAD

**Issue by synalysis** [elm/compiler#1930]
**Quick Summary:** ???
When producing optimized code a JavaScript runtime error can be produced by this code:
    Task.attempt (\_ -> NoOp) <| Dom.setViewportOf "unknown-id" 0 0

## SSCCE
How to reproduce:
- uncompress
[setviewportof-test.zip](https://github.com/elm/compiler/files/3153181/setviewportof-test.zip)
- elm-app build
- serve build
- navigate to http://localhost:5000/
- click the button

```elm
module Main exposing (Model, Msg(..), init, main, scrollToTop, update, view)

import Browser
import Browser.Dom as Dom
import Html exposing (Html, button, div, text)
import Html.Attributes exposing (src)
import Html.Events exposing (onClick)
import Task



---- MODEL ----


type alias Model =
    {}


init : ( Model, Cmd Msg )
init =
    ( {}, Cmd.none )



---- UPDATE ----


type Msg
    = NoOp
    | ScrollToTop


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        NoOp ->
            ( model, Cmd.none )

        ScrollToTop ->
            ( model, scrollToTop )


scrollToTop : Cmd Msg
scrollToTop =
    Task.attempt (\_ -> NoOp) <| Dom.setViewportOf "unknown-id" 0 0



---- VIEW ----


view : Model -> Html Msg
view model =
    div []
        [ button [ onClick ScrollToTop ] [ text "scroll non-existing" ]
        ]



---- PROGRAM ----


main : Program () Model Msg
main =
    Browser.element
        { view = view
        , init = \_ -> init
        , update = update
        , subscriptions = always Sub.none
        }

```

- **Elm:** 0.19
- **Browser:** tested with Chrome and Safari
- **Operating System:** macOS 10.14.4

## Additional Details
The error message:
```
Main.elm:4153 Uncaught TypeError: rr is not a function
    at Main.elm:4153
```

```
function _Browser_withNode(id, doStuff)
{
	return _Scheduler_binding(function(callback)
	{
		_Browser_requestAnimationFrame(function() {
			var node = document.getElementById(id);
			callback(node
				? _Scheduler_succeed(doStuff(node))
				: _Scheduler_fail(elm$browser$Browser$Dom$NotFound(id))
			);
		});
	});
}
```
For some reason _Scheduler_fail is not defined in this context.

**Comment by zwilias** [comment]
I think this is the same issue as #1836. Duplicate issues are okay, no worries!

I'm mentioning it because [Evan's comment](https://github.com/elm/compiler/issues/1836#issuecomment-463037320) there is useful information:
> There is a fix for this, but just to set time expectations, there is quite a bit of work left before a 0.19.1 release is possible. In particular, I found some performance issues caused by laziness that require some larger changes to address reliably. Anyway, thank you for the report!

**Comment by synalysis** [comment]
Thanks, good to know. Now it can also be found with the "TypeError" error message :-)
