### ISSUE TITLE
0.19.0-no-deps version does not run within npm script

### ISSUE THREAD

**Issue by MikeTschudi** [elm/compiler#1932]
**Quick Summary:**
`0.19.0` works on the command line and within the npm script ; `0.19.0-no-deps` works on the command line but fails in script. Reverting to `elm@0.19.0` restores capability

## SSCCE

```elm
OK:  elm make src/main.elm --output=src/main.js
not OK: in package.json's scripts
   "build1": "elm make src/main.elm --output=src/main.js"
```

- **Elm:** 0.19.0-no-deps
- **Browser:** n/a
- **Operating System:** Windows 10 Enterprise

## Additional Details
command prompt window:
```
npm run build1

> online@0.0.1 build1 C:\Users\...\online
> elm make src/main.elm --output=src/main.js

The process cannot access the file because it is being used by another process.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! online@0.0.1 build1: `elm make src/main.elm --output=src/main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the online@0.0.1 build1 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2019-05-13T22_27_56_184Z-debug.log
```

**Comment by evancz** [comment]
I am unclear how to reproduce this based on the information here. Can you include the full `package.json` file you are using? If there are additional files involved, please share those as well!

**Comment by MikeTschudi** [comment]
Sure!  Here are the steps starting with an empty Windows folder:
* npm init *(I'm using npm version 6.9.0)*
* npm install elm
* edit package.json to add `"build1": "elm make src/main.elm --output=src/main.js"`
* mkdir src
* added src/main.elm using [first example](https://guide.elm-lang.org/architecture/buttons.htm) in the Elm Guide
* npm run build1
* elm make src/main.elm --output=src/main.js
* elm init
* npm run build1
* elm make src/main.elm --output=src/main.js

The two `npm run build1` lines produce the error above; the first `elm make` reminds me to run `elm init`; the second `elm make` works.

package.json & src/main.elm attached: [no-deps.zip](https://github.com/elm/compiler/files/3183272/no-deps.zip)

---

If I then run
* npm install elm@0.19.0
* npm run build1
* elm make src/main.elm --output=src/main.js

Both build paths work

**Comment by evancz** [comment]
Thanks, I am asking some other folks about this to try to figure out what might be happening. If you want to get some faster assistance, please ask around in [the Elm Slack](https://elmlang.herokuapp.com/) and share what you learn here!

**Comment by harrysarson** [comment]
I have tried and failed to reproduce on windows 10 cmd.

I did get an error when running `elm make` if directory (or its parent directory, etc) does not contain an `elm.json` file. Adding an `elm.json` file (by running `$ elm init` or otherwise) fixes this error.

For example:
```
$ ls -R
.:
main.js  src

./src:
Main.elm

$ elm make src/Main.elm
-- FILE NOT FOUND --------------------------------------------------------------

You want me to compile this file:

    src/Main.elm

I cannot find it though! Is there a typo?

$ elm init
-- snip --

$elm make src/Main.elm                                                                            
Dependencies loaded from local cache.                                                                                   
Dependencies ready!                                                                                                     
Success! Compiled 1 module.    

```

I get the same error if using an npm build script and I also get the same error using the old elm 19 npm package. I could not reproduce the `The process cannot access the file because it is being used by another process.` error by following the instructions or otherwise.

I found that including `--output=src/main.js` made no difference.

Hope that helps!

**Comment by evancz** [comment]
Let's try to get it down to more of an SSCCE. I am expecting something like this, with everything necessary inline in the thread:

## Example

My trouble is demonstrated by the following `package.json`:

```json
{
  "name": "no-deps",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build1": "elm init"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "elm": "0.19.0-no-deps"
  }
}
```

When I run `npm run build1` I get an error.

But when I change to `"elm": "0.19.0-bugfix6"` I do not get an error.

* * *

I don't know if that actually manifests the bug you are seeing, but a SSCCE would be something like that. Where the whole problem can be explained in one file.

Please open a fresh issue with that in the initial comment. And please ask around for help on Slack if you are unclear how to proceed!

**Comment by rtfeldman** [comment]
As one data point, I ran [the steps in this comment](https://github.com/elm/compiler/issues/1932#issuecomment-492705562) with two fixes:
* The link to the Guide 404'd due to a stray `l` at the end - I used [this one](https://guide.elm-lang.org/architecture/buttons.html) instead
* I added `"build1"` to `"scripts"` (not to top-level `package.json`) because otherwise `npm run` won't find it

Everything worked with no errors.

Here's the `package.json` I ended up with:

```
{
  "name": "elminstalltest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build1": "elm make src/main.elm --output=src/main.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "elm": "0.19.0-no-deps"
  }
}
```

**Comment by MikeTschudi** [comment]
Thanks for catching the URL error, @rtfeldman. I appreciated the background idea because I was running VSCode as well with the Elm plugin. I rebooted and only ran the command line version, but it still failed.

**Comment by MikeTschudi** [comment]
Thanks for the SSCCE, @panthus
