### ISSUE TITLE
Running elm version 0.19.0-no-deps from an npm script fails

### ISSUE THREAD

**Issue by panthus** [elm/compiler#1934]
**Quick Summary:**
Running `elm make` from an npm script results in: 
`The process cannot access the file because it is being used by another process.`

Duplicate of #1932

## SSCCE

Running `npm install` and then `npm run build` from a directory containing the following `package.json` results in the error above. I think it depends on the speed of the hard drive/computer or presence of a virus scanner if the issue happens or not, as it is caused by a race condition between the download script and the spawn of the elm executable.
```elm
{
  "name": "no-deps",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build": "elm init"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "elm": "0.19.0-no-deps"
  }
}
```

- **Elm:** 0.19.0
- **Browser:** N/A
- **Operating System:** Windows 7

## Additional Details

```
$ npm run build

> no-deps@1.0.0 build C:\test
> elm init

The process cannot access the file because it is being used by another process.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! no-deps@1.0.0 build: `elm init`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the no-deps@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\teugis\AppData\Roaming\npm-cache\_logs\2019-05-17T11_42_36_924Z-debug.log
```

## Cause
On windows it tries to use `node_modules\elm\bin\elm` when you run elm via an npm script. This results in the download.js script starting to download the elm executable, even if it already exists. Apparently the spawn of the elm executable happens before the download script has completely released the file. It is also possible that a virus scanner is somehow interfering here.

## Possible solution
A possible solution would be to detect if the executable already exists and then not download it, which would prevent the possibility of a race condition with the file locks between downloading and spawning the elm executable (at least in the case where the elm executable already exists on disk).

Changing the export in `download.js` to the code below ensures the elm executable is not downloaded if it already exists and solves the issue for me.
```javascript
module.exports = function(destinationPath, callback)
{
	var version = package.version.replace(/^(\d+\.\d+\.\d+).*$/, '$1'); // turn '1.2.3-alpha' into '1.2.3'
	var os = { 'darwin': 'mac', 'win32': 'windows', 'linux': 'linux' }[process.platform];
	var arch = { 'x64': '64-bit', 'ia32': '32-bit' }[process.arch];
	var path = process.platform === 'win32' ? destinationPath + '.exe' : destinationPath;
	
	fs.open(path, 'r', function (error, fd) {
		if (error) {
			download(
				path,
				'https://github.com/elm/compiler/releases/download/' + version + '/binary-for-' + os + '-' + arch + '.gz',
				callback
			);
		} else {
			callback();
		}
	});
};
```

**Comment by jordanwilcken** [comment]
Same problem here. Installing 19 using Windows installer works fine. Can't run elm commands after npm install because `The process cannot access the file because it is being used by another process.`

**Comment by rtfeldman** [comment]
> Running `npm install` and then `npm run build`

Huh, so I guess "and then" in this case means *instantaneously* after—as in, `npm install && npm run build`, not "I typed `npm install` and then when that command finished I typed `npm run build` and pressed Enter again." I'd guess with the latter there would be too much of a time gap to trigger a race condition like this. 🤔

**Comment by rtfeldman** [comment]
@panthus One concern I have about this proposed solution is that on non-Windows systems, I expect this conditional would always pass because the name of the downloaded binary will be `elm` (not `elm.exe`) and there will already be a file called `elm` there.

(On non-Windows systems, the previous `elm` is replaced by the downloaded one; Windows is unusual in this regard because it requires adding a `.exe` extension.)

**Comment by panthus** [comment]
> > Running `npm install` and then `npm run build`
> 
> Huh, so I guess "and then" in this case means _instantaneously_ after—as in, `npm install && npm run build`, not "I typed `npm install` and then when that command finished I typed `npm run build` and pressed Enter again." I'd guess with the latter there would be too much of a time gap to trigger a race condition like this. 🤔

I ran them one by one. After thinking about it some more I am pretty sure it is the virus scanner. 

> @panthus One concern I have about this proposed solution is that on non-Windows systems, I expect this conditional would always pass because the name of the downloaded binary will be `elm` (not `elm.exe`) and there will already be a file called `elm` there.
> 
> (On non-Windows systems, the previous `elm` is replaced by the downloaded one; Windows is unusual in this regard because it requires adding a `.exe` extension.)

I was afraid that was the intention. Right now it downloads the elm executable every time I try to run an elm command (no matter if the .exe already exists or not)... 

Since the `elm` file is not overwritten it triggers a download each time it is executed. Then immediately after the download it tries to spawn the executable but since it was just downloaded my virus scanner is still scanning the file which causes the file in use error.

- Perhaps it would be a better solution to have the download script remove the `elm` file or have it replaced by a file that only spawns the .exe instead of download and then spawn.
- Or perhaps have the wrappers in `node_modules/.bin` call the .exe instead of the `elm` file (this would also be quicker as you do not have to spawn node.exe).

**Comment by panthus** [comment]
Hmm, how does this work on Linux or macos. The `elm` javascript file is replaced with the elm executable, but the wrappers in `node_modules/.bin` try to execute that `elm` file with node.exe, which will fail because that file is no longer a javascript file?

Or are those wrapper files different on Linux and macos?

**Comment by ulisses-alves** [comment]
Could this be in any way related to https://github.com/parcel-bundler/parcel/issues/3042 ?

**Comment by panthus** [comment]
> 
> 
> Could this be in any way related to [parcel-bundler/parcel#3042](https://github.com/parcel-bundler/parcel/issues/3042) ?

If parcel uses elm via the npm package then changes are high that it does. Every time you run `elm make` using elm from the npm package triggers a download of the elm executable (even if you already have the executable on disk...). File downloads are usually intercepted by a virus scanner and this means the virus scanner could lock the file when elm tries to execute it.

**Comment by panthus** [comment]
An easy workaround is to downgrade the elm npm package to version 0.19.0-bugfix6.

**Comment by roebuk** [comment]
I've tried downgrading to `bugfix5` and `bugfix6` and I'm still getting this error when running through Parcel.

**Comment by Ryan1729** [comment]
On a slow connection, waiting for the exe to download, every time, before the actual command is run, is an awful experience. Particularly since no feedback that that is happening is given. As might be expected, this problem affects Windows 10 as well as 7.

One of these two solutions suggested by @panthus seem like the best way forward.

>     * Perhaps it would be a better solution to have the download script remove the `elm` file or have it replaced by a file that only spawns the .exe instead of download and then spawn.
> 
>     * Or perhaps have the wrappers in `node_modules/.bin` call the .exe instead of the `elm` file (this would also be quicker as you do not have to spawn node.exe).

In the meantime, manually replacing `node_modules\elm\bin\elm` with the following is a workaround, (I just cut out the download portions of the existing script):

```js
#!/usr/bin/env node

var child_process = require('child_process');
var fs = require('fs');

// Make sure we get the right path even if we're executing from the symlinked
// node_modules/.bin/ executable
var pathToThisFile = fs.realpathSync(process.argv[1]);

// Need double quotes and { shell: true } when there are spaces in the path on windows:
// https://github.com/nodejs/node/issues/7367#issuecomment-229721296
child_process
.spawn('"' + pathToThisFile + '"', process.argv.slice(2), { stdio: 'inherit', shell: true })
.on('exit', process.exit);
```

**Comment by evancz** [comment]
Does this persist with `npm install elm@latest-0.19.1`?

**Comment by Ryan1729** [comment]
That version seems to have fixed it for me. I can see in the `node_modules/elm/bin/elm` file that there is now a special code path for Windows.

I'll note that the `latest-0.19.1` version also currently brings in 47 other folders into `node_modules` where the previous version only added the `elm` folder. But not having to mess with the scripts to get things working acceptably on a slow connection is a definite improvement!

**Comment by ulisses-alves** [comment]
The issue is also gone for me as well. Thanks for the hard work :)

**Comment by panthus** [comment]
> Does this persist with `npm install elm@latest-0.19.1`?

That fixes the issue for me too, thanks a lot! :)
