### ISSUE TITLE
One-time compiler error for subscription

### ISSUE THREAD

**Issue by bdrp** [elm/compiler#1936]
**Quick Summary:**

A subscription can miss some parameters to an update message and it will still compile successfully. When running, it will cause a javascript runtime error.

## SSCCE

Sample incorrect code:
```elm
type Msg
    -- Message received when a key is pressed. Parameters: key pressed, x coord, y coord
    = NewKeyPress String Int Int
    -- "Enter" was pressed, submit coordinates
    | SubmitNew Int Int
    -- "Cancel" was pressed, do nothing
    | CancelNew

-- Does the model have a coordinate stored? Then check for key press
subscriptions model =
    Sub.batch
        [ case model.openNew of
            Just ( x, y ) ->
                Event.onKeyDown <|
                    Decode.map NewKeyPress
                        (Decode.field "key" Decode.string)

            _ ->
                Sub.none
        ]

update msg model =
    case msg of
        NewKeyPress key x y ->
            ( model
            , case key of
                "Enter" ->
                    Task.succeed SubmitNew |> Task.perform (\a -> a x y)

                "Escape" ->
                    Task.succeed CancelNew |> Task.perform identity

                _ ->
                    Cmd.none
            )

        SubmitNew x y ->
            ( { model | openNew = Nothing }
            , createNew <| Node.createEmptyNode model.newName x y
            )

        CancelNew ->
            ( { model | openNew = Nothing }, Cmd.none )
```
Pressing a key will cause a runtime error. Correct subscriptions code looks like this:
```elm
subscriptions model =
    Sub.batch
        [ case model.openNew of
            Just ( x, y ) ->
                Event.onKeyDown <|
                    Decode.map3 NewKeyPress
                        (Decode.field "key" Decode.string)
                        (Decode.succeed x)
                        (Decode.succeed y)

            _ ->
                Sub.none
        ]
```
Once changed, the code will cause a compiler error if I try to change it back.

- **Elm:** 0.19.0
- **Browser:** Vivaldi 2.5.1525.41 (Stable channel) (64-bit)
- **Operating System:** Windows 10

**Comment by harrysarson** [comment]
Would it be possible to share a version I can run? 

I currently get errors like 
```
Line 47, Column 15
I cannot find a `createNew` variable:
```
and there is no main function.

**Comment by bdrp** [comment]
Seems this has something to do with the autosave option in VS Code. I get many different weird errors when using autosave. They disappear when saving files manually.

**Comment by evancz** [comment]
I am going to share this information with the folks who I know make plugins for VS Code. It seems like a lot of folks who have reporting troubles with `elm make` leading to weird file issues are also using VS Code.

I have made changes to `elm` to make it more resilient to being called multiple times on the same project at the same time, but it's still not a good idea to do that.

Thank you for the report!
