### ISSUE TITLE
Type variable change not recognized in case matching

### ISSUE THREAD

**Issue by FranzSkuffka** [elm/compiler#1939]
**Quick Summary:**
I am using the RemoteData package which exposes the type
```elm
type RemoteData e a
    = NotAsked
    | Loading
    | Failure e
    | Success a
```

My map function works if I write it like this
```elm
mapSuccess : (a -> b) -> (RemoteData.WebData a -> RemoteData.WebData b)
mapSuccess fn webData =
  case webData of
    Success data -> Success (fn data)
    Failure f -> Failure f
    NotAsked -> NotAsked
    Loading -> Loading
```

But not if I use a catch-all below the `Success` case. See SSCCE

## SSCCE

```elm
type RemoteData e a
    = NotAsked
    | Loading
    | Failure e
    | Success a


mapSuccess : (a -> b) -> (RemoteData.WebData a -> RemoteData.WebData b)
mapSuccess fn webData =
  case webData of
    Success data -> Success (fn data)
    notSuccess -> notSuccess
```
The error is
```
     notSuccess -> notSuccess
                       ^^^^^^^^^^
This `notSuccess` value is a:

    RemoteData.WebData a

But the type annotation on `mapSuccess` says it should be:

    RemoteData.WebData b
```

I expect this to not throw an error as the type referred to by the type variable in the `WebData` type is changed in the first case and no other cases contain this type.

- **Elm:** Elm 0.19.0-bugfix6
- **Browser:** -
- **Operating System:** macOS Mojave 10.14.5 (18F132)

**Comment by jhrcek** [comment]
@FranzSkuffka this is actually not a bug, but correct behavior. Despite the type parameter `a` not being used in the other cases you still need to deconstruct and reconstruct those patterns to change the type.

Without this behavior it would be for example impossible to use "advanced" techniques like [phantom types](https://medium.com/@ckoster22/advanced-types-in-elm-phantom-types-808044c5946d) where you have a type variable only present in a type (and not present at the value level) and you rely on compiler to prevent you from mixing up instances of that type differing in the type parameter.

**Comment by FranzSkuffka** [comment]
I understand that phantom types add another layer of security. However I must contradict in my understanding.
```
type PhantomType a = PhantomType String | PhantomType_ String
type APhantomType a b
    = Tag1 b
    | Tag2

map : (b -> c) -> APhantomType a b ->  APhantomType a c
map fn instance =
  case instance of
    Tag1 b -> Tag1 (fn b)
    rest -> rest
```
In the above example, the function does not corrupt the phantom type because it is referred to with `a` in both cases. Below is an invalid and bad example because the function changes the type annotation just by means of type annotation. I think of Phantom types as in blockers in the compatibility with specific other types and in the case below we have the type annotation mutating the phantom type
```elm
map : (b -> c) -> APhantomType a b ->  APhantomType d c
map fn instance =
  case instance of
    Tag1 b -> Tag1 (fn b)
    rest -> rest
```

Whereas I think this here would be valid because the instance is reconstructed entirely.
```elm
map : (b -> c) -> APhantomType a b ->  APhantomType a c
map fn instance =
  case instance of
    Tag1 b -> Tag1 (fn b)
    Tag2 -> Tag2
```

Summary in of my understanding how it should work:
- to change phantom types, an instance must be reconstructed entirely
- to change type variables, only the usages must be mapped

**Comment by evancz** [comment]
This is one of the somewhat surprising characteristics of ML-family type inference. I expect you will find the same behavior in languages like StandardML, OCaml, and Haskell.

In one of the examples you gave:

```
type APhantomType a b
    = Tag1 b
    | Tag2

map : (b -> c) -> APhantomType a b ->  APhantomType a c
map fn instance =
  case instance of
    Tag1 b -> Tag1 (fn b)
    rest -> rest
```

The issue is that `instance` has type `APhantomType a b`, and therefore all the patterns in the `case` are also of type `APhantomType a b`. So when you use `rest` on the right-hand side of the arrow, it still has type `APhantomType a b`.

The tricky thing is that the type system is not able to specialize for specific scenarios like you are describing. It is true that `Tag2` could be any type of `APhantomType a b` without any changes, but from the perspective of the type system, it is just one type.

(This further interacts with the concept of "rigid type variables" that you use in the type annotation.)

I'm not sure this explanation is helpful, but to prove to yourself that it is not a bug in Elm in particular, it may be worth trying out other ML-family programming languages to see how they work. E.g. I just tried this in Haskell and got this error message:

```
temp.hs:9:13: error:
    • Couldn't match type ‘b’ with ‘c’
      ‘b’ is a rigid type variable bound by
        the type signature for:
          Main.map :: forall b c a. (b -> c) -> Example a b -> Example a c
        at temp.hs:5:1-46
      ‘c’ is a rigid type variable bound by
        the type signature for:
          Main.map :: forall b c a. (b -> c) -> Example a b -> Example a c
        at temp.hs:5:1-46
      Expected type: Example a c
        Actual type: Example a b
    • In the expression: rest
      In a case alternative: rest -> rest
      In the expression:
        case arg of
          Tag1 b -> Tag1 (fn b)
          rest -> rest
    • Relevant bindings include
        rest :: Example a b (bound at temp.hs:9:5)
        arg :: Example a b (bound at temp.hs:6:8)
        fn :: b -> c (bound at temp.hs:6:5)
        map :: (b -> c) -> Example a b -> Example a c
          (bound at temp.hs:6:1)
  |
9 |     rest -> rest
  |             ^^^^
```

Hopefully that helps!
