### ISSUE TITLE
elm reactor not serving .webp

### ISSUE THREAD

**Issue by ampheul** [elm/compiler#1942]
**Quick Summary:** elm reactor does not serve .webp images as it should. [related issue](https://github.com/elm-lang/elm-reactor/issues/190) in the old repo never marked closed.

## SSCCE

```elm

```

- **Elm:** 0.19.0
- **Browser:** Firefos 67
- **Operating System:** Xubuntu 19.04

## Additional Details

???

**Comment by evancz** [comment]
It looks like since that previous issue the support has gotten better. Looks like only Safari does not support it at this time. Thanks for moving the issue to the new repo!
