### ISSUE TITLE
Allow shadowing of variables that are not yet accessible

### ISSUE THREAD

**Issue by simonolander** [elm/compiler#1953]
**Quick Summary:**
Sometimes you have a bunch of variables that depend on some shared condition. In those cases I find it useful to compute them in a nested let statement and then get them through deconstruction in the outer scope. The reason being to avoid code duplication or partial results leaking into the outer scope.

In those cases I want to use the same variable name, since it's literally the same value being propagated, but this causes the compiler to complain about shadowing. There is however no ambiguity as to which variable is being referenced, since the destructured values can't be referenced until the inner body is evaluated.

## SSCCE

```elm
f =
    let
        { a, b, c, d } =
            let
                a =
                    0

                { b } =
                    { b = 0 }

                ( c, d ) =
                    ( 0, 0 )
            in
            { a = a, b = b, c = c, d = d }
    in
    a + b + c + d
```
I believe this should be legal. All the variables in this example gets marked as shadowed, but there isn't actually any ambiguity as to which variable every reference is referring.

- **Elm:** 0.19.0

**Comment by evancz** [comment]
I know a couple cases where shadowing is quite useful. The best example is if you are threading some `state` around. You can use shadowing to make sure you are always passing the most recent definition through.

So I know there are cases where it'd be handy, but it seems on balance to be worthwhile to keep the existing behavior.

**Comment by simonolander** [comment]
I think you understand what I was trying to say, but just for emphasis: I don't think these are instances of shadowing. I think removing shadowing in general is a good idea. With that said, if you reconsider I'm happy but this is little more than an annoyance.
