### ISSUE TITLE
elm binary gets downloaded on every elm command on Windows when using the latest npm installer

### ISSUE THREAD

**Issue by harmboschloo** [elm/compiler#1957]
After installing elm using the npm installer with version `0.19.0-no-deps` on Windows the elm binary (`elm.exe`) is downloaded on every elm command. This makes executing any command really slow. 

The binary should only be downloaded if it doesn't exist. In the version `0.19.0-bugfix6` there is a check of this in `node_modules\elm\bin\elm` but that was removed in the `0.19.0-no-deps`.

I think this is only a Windows issue. On Linux I think the `node_modules\elm\bin\elm` script actually gets replaced with the binary file. But since on Windows that filename isn't the same this does not work on Windows.

A solution might be to check for the `elm.exe` binary in the `elm.cmd` file. If it exists it can be called directly, if not it should be downloaded.

**Comment by evancz** [comment]
There is logic added for that [here](https://github.com/elm/compiler/blob/master/installers/npm/download.js#L23-L26) but I have not gotten a chance to test it on Windows yet.

I'd like to get it tested before 0.19.1 is ready so it can come out then with no problems. Are you able to test this version of the code?

**Comment by harmboschloo** [comment]
Yes, that works for me. Tested on Window 10, node v10.15.3

**Comment by movefasta** [comment]
> 
> 
> There is logic added for that [here](https://github.com/elm/compiler/blob/master/installers/npm/download.js#L23-L26) but I have not gotten a chance to test it on Windows yet.
> 
> I'd like to get it tested before 0.19.1 is ready so it can come out then with no problems. Are you able to test this version of the code?

works fine. Windows 10, node v10.15.3

**Comment by evancz** [comment]
This should be resolved with `npm install elm@latest-0.19.1`. Can you confirm?

**Comment by evancz** [comment]
Please open a new issue about `latest-0.19.1` if the issue persists!
