### ISSUE TITLE
can't install elm on ubuntu 19.04

### ISSUE THREAD

**Issue by abuakram** [elm/compiler#1958]
ubuntu 19.04
> npm install -g elm
produced following log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', 'elm' ]
2 info using npm@6.10.0
3 info using node@v12.7.0
4 verbose config Skipping project config: /home/***/.npmrc. (matches userconfig)
5 verbose npm-session a491879c9a532655
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 304 https://registry.npmjs.org/elm 925ms (from cache)
9 silly pacote tag manifest for elm@latest fetched in 939ms
10 timing stage:loadCurrentTree Completed in 1003ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule elm@0.19.0-no-deps checking installable status
18 silly removeObsoleteDep removing elm@0.19.0-no-deps from the tree as its been replaced by a newer version or is no longer required
19 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 6ms
20 timing stage:loadIdealTree Completed in 11ms
21 silly currentTree ***
21 silly currentTree └── elm@0.19.0-no-deps
22 silly idealTree ***
22 silly idealTree └── elm@0.19.0-no-deps
23 silly install generateActionsToTake
24 warn checkPermissions Missing write access to /home/***/node_modules/elm
25 warn checkPermissions Missing write access to /home/***/node_modules
26 timing stage:rollbackFailedOptional Completed in 1ms
27 timing stage:runTopLevelLifecycles Completed in 1025ms
28 silly saveTree ***
28 silly saveTree └── elm@0.19.0-no-deps
29 warn enoent ENOENT: no such file or directory, open '/home/***/package.json'
30 verbose enoent This is related to npm not being able to find a file.
31 warn *** No description
32 warn *** No repository field.
33 warn *** No README data
34 warn *** No license field.
35 verbose stack Error: EACCES: permission denied, access '/hom/***/node_modules/elm'
36 verbose cwd /home/***
37 verbose Linux 5.0.0-21-generic
38 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "elm"
39 verbose node v12.7.0
40 verbose npm  v6.10.0
41 error path /home/***/node_modules/elm
42 error code EACCES
43 error errno -13
44 error syscall access
45 error Error: EACCES: permission denied, access '/home/***/node_modules/elm'
45 error  [Error: EACCES: permission denied, access '/home/***/node_modules/elm'] {
45 error   stack: "Error: EACCES: permission denied, access '/home/***/node_modules/elm'",
45 error   errno: -13,
45 error   code: 'EACCES',
45 error   syscall: 'access',
45 error   path: '/home/***/node_modules/elm'
45 error }
46 error The operation was rejected by your operating system.
46 error It is likely you do not have the permissions to access this file as the current user
46 error
46 error If you believe this might be a permissions issue, please double-check the
46 error permissions of the file and its containing directories, or try running
46 error the command again as root/Administrator (though this is not recommended).
47 verbose exit [ -13, true ]

**Comment by evancz** [comment]
All that the npm install route is doing is downloading a binary from https://github.com/elm/compiler/releases/tag/0.19.0, so you can get unstuck by downloading it directly.

The error message you are showing here is saying that there may be a permissions issue:

```
It is likely you do not have the permissions to access this file as the current user
```

I have seen this kind of thing happen with `npm` recently. I usually try adding `sudo` or searching online for the particular `npm` error. Do you think this is something specific to Elm though?

**Comment by abuakram** [comment]
@evancz, thanks for your response...
Tried with sudo ... didn't work ... same response
Guess I should try the binary file.

**Comment by Razzeee** [comment]
I'm wondering about the path `/home//node_modules/elm` did you remove you username from the output? otherwise that would be weird / a problem.

**Comment by evancz** [comment]
This doesn't seem like a bug in Elm itself, so I recommend asking for help in [the Elm slack](https://elmlang.herokuapp.com/) where folks can give you feedback really quickly. This seems like something a lot of folks have experience with, and they can probably give good recommendations in that format!
