### ISSUE TITLE
Release 0.19 Linux 32bit is a 64bit version

### ISSUE THREAD

**Issue by fstiffo** [elm/compiler#1962]
The binaries for Linux 32bit 

https://github.com/elm/compiler/releases/download/0.19.0/binaries-for-linux.tar.gz

are a 64bit version

Try this on the executable:

file elm
elm: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, with debug_info, not stripped

## SSCCE

```elm

```

- **Elm:** 0.19
- **Browser:** --
- **Operating System:** Ubuntu 18.04 32bit

## Additional Details

None

**Comment by rlefevre** [comment]
Where does it say 32bits?

**Comment by fstiffo** [comment]
Ok, then there are 2 version for Linux 64bit with different names? 

binaries-for-linux.tar.gz

and

binary-for-linux-64-bit.gz

?

**Comment by rlefevre** [comment]
You're right, this is not clear, and there is the same ambiguity for windows and mac:

https://github.com/elm/compiler/releases/

**Comment by evancz** [comment]
The `.tar.gz` version exists for old versions of the `npm` installer. The latest release only has the `.gz` files.

We do not currently plan to do official builds for 32-bit architectures. What is the usage scenario? That information can help us weigh the benefits and may change the prioritization decision.

**Comment by evancz** [comment]
Tracking in https://github.com/elm/compiler/issues/2007.

Still would really like to know the usage scenario for the 32-bit computer. Is it an old computer? Is it a special kind of device? Etc.

**Comment by jteg68** [comment]
I would use a 32-bit linux version at home, for trying out elm. Having had some troubles with haskell & cabal a long time ago building from source is not something i look forward to.
This is a low priority for me at the moment.

**Comment by rlefevre** [comment]
@jteg68 You actually did not tell why this would require a 32-bit binary

> Is it an old computer? Is it a special kind of device? Etc.

**Comment by MarkDBlackwell** [comment]
An old computer at home is my use case for an Elm 32-bit binary. Actually, while working at home, I like to relax with an old Linux laptop.

**Comment by tasuki** [comment]
I have an old computer in the cloud and would also appreciate a 32-bit binary. Or, better still, an installation process that doesn't rely on curling binaries.

**Comment by rlefevre** [comment]
@MarkDBlackwell, @tasuki , what 32bit Linux distribution and version do you use?

@tasuki What do you mean about the installation process? Downloading a single binary is as simple as it can get. You can also use the [`npm` package](https://www.npmjs.com/package/elm) or the [nix package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/elm/packages/elm.nix) if you want.

**Comment by MarkDBlackwell** [comment]
The 32bit Linux distribution and version I use is Debian 10.3 (Buster).

**Comment by rlefevre** [comment]
@MarkDBlackwell You can give a try at the i386 binaries built on Debian 10 Buster with Docker here:
https://gist.github.com/rlefevre/8fcf368d9951137e9e810c06c111bba1

Please reports issues only in the gist, those are completely unofficial.

**Comment by dullbananas** [comment]
I am using an Alpine Linux emulator on my iPad, and I want to easily install Elm on it, but [it doesn't have 64 bit emulation](https://github.com/ish-app/ish/issues/1383). I also wish it was possible to just `apk add elm`. I hate the current installing process!
