### ISSUE TITLE
case of redundant pattern

### ISSUE THREAD

**Issue by bra1nDump** [elm/compiler#1976]
Values
```
  (Just False, true)
  (Nothing, true)
```
should be falling to the case C

```elm
-- REDUNDANT PATTERN ---------------------------------------------- src/Main.elm
The 3rd pattern is redundant:

119|             case (maybe, boolean) of 
120|                 (Just True, _) -> A
121|                 (_, false) -> B
122|                 _ -> C
                     ^
Any value with this shape will be handled by a previous pattern, so it should be
removed.
```

- Elm: 0.19.0
- Operating System: macOS Mojave 10.14.6

### Additional info
- actual names were replaced for simplicity
- both  `maybe, boolean` values are fields in the same record

**Comment by FranzSkuffka** [comment]
This is not a bug. If you look closely, your second condition is `(_, false) -> B`. Here, `false` is lowercase and thus treated like a variable. If you use uppercase `False` it should work as expected.

**Comment by bra1nDump** [comment]
Thanks for finding my problem, I looked at it like 10 times to make sure, but I guess at that point you see what you want to see :)

**Comment by FranzSkuffka** [comment]
Sometimes you just need a break. Or some help :)
