### ISSUE TITLE
Mutually recursive "pointless" function definitions gives cyclic value error

### ISSUE THREAD

**Issue by allanderek** [elm/compiler#1983]
**Quick Summary:**

If you define a mutually recursive pair of functions where one of them is defined without explicit arguments you get an error about a cyclic definition, although the pair of functions are valid, in the sense that you could reasonably expect them to compile. You can easily give what is an equivalent definition that is allowed by the compiler as shown below.

The problem appears to occur when you're defining what is a function but uses partial application of another function rather than explicitly containing arguments.
This is probably best described with an example:

## SSCCE

```elm
module SSCCE exposing (gather)

type Tree =
    Node Int (List Tree)
    
gather : Tree -> List Int
gather =
    let
        gatherList : List Tree -> List Int
        gatherList =
            (List.map gatherSingle) >> List.concat

        gatherSingle : Tree -> List Int
        gatherSingle tree =
           case tree of
                Node i children ->
                    i :: gatherList children


    in
    gatherSingle
    
```
This gives the error regarding cyclic definitions within a `let`:

```
cyclic value
Line 10, Column 9
I do not allow cyclic values in `let` expressions.

10|         gatherList =
            ^^^^^^^^^^
The `gatherList` value depends on itself through the following chain of
definitions:

    ┌─────┐
    │    gatherList
    │     ↓
    │    gatherSingle
    └─────┘

Hint: The root problem is often a typo in some variable name, but I recommend
reading <https://elm-lang.org/0.19.0/bad-recursion> for more detailed advice,
especially if you actually do want mutually recursive values.
```

You can fix this and compile it by simply adding the explicit argument to `gatherList`:

```
      gatherList trees =
            ((List.map gatherSingle) >> List.concat) trees
```

- **Elm:** 0.19.0
- **Browser:** N/A
- **Operating System:** Manjaro Linux, but I believe unimportant

## Additional Details

This is of course arguably not a bug. There needs to be some rule for when you are and are not allowed to define something that references itself. It's possible that keeping the rule simple is better than being less conservative in which definitions to allow (and therefore allowing more valid definitions). It's also possible that there is just no way to definitely rule out invalid recursive definitions whilst allowing this kind of valid recursive definition.

If the current rule is kept I thought this issue worth it just to have the discussion and/or document the decision.

**Comment by evancz** [comment]
We used to have problems with recursive values based on the order they were declared. I wrote about that here:

https://gist.github.com/evancz/07436448b7d6c947f21742dab46d1218

This document ended up leading to the following design:

- Recursive functions (with arguments) are allowed anywhere in Elm code.
- Recursive values (without arguments) are only allowed at the top level.

One of the nice things about this design is that it is not possible to dynamically allocate cyclic values, so some future GC implementation for Elm can be simpler and possibly faster as a result.

As an aside: I very highly recommend having named arguments for all functions, so I personally think the ability to leave off arguments in more cases would be a downside from a design perspective.

Anyway, I hope that gives more insight into the design considerations that went into figuring out when recursive values are alright!
