### ISSUE TITLE
Performance problem with multi-level extended record

### ISSUE THREAD

**Issue by austinshenk** [elm/compiler#1987]
**Quick Summary:** I'm having an issue getting a record to compile that has about 6 or 7 levels deep of extension

## SSCCE
I'm doing just some basic record extensions by defining records in separate files for organization sake that extend other records that have extensions. https://github.com/austinshenk/elm-wai/tree/f3c816005378001d9a450e111afec31810ffe92f/src/Wai/Role has all the files that I've tried defining, but not successfully compiled. [Abstract/RoleType.elm](https://github.com/austinshenk/elm-wai/blob/f3c816005378001d9a450e111afec31810ffe92f/src/Wai/Role/Abstract/RoleType.elm) is the parent type and then sub types are imported in.

Since this is a package I've been checking it by running `elm-test`. It almost completes, but the compiler hangs forever and consumes all machine resources. CPU jumps to 100% immediately and memory slowly starts to be completely consumed as well. Seems like a performance problem when verifying record type fields or something.

- **Elm:** 0.19.0-bugfix6
- **Operating System:** Mac 10.13.6 (17G6030)

**Comment by albertdahlin** [comment]
I think this is the same as #1897

**Comment by austinshenk** [comment]
That's exactly the use case that I've been seeing for this issue. Basically, creating a record from a bunch of other records seems to be really slow. My only workaround right now is to hard code pieces of it to limit the amount of records that I'm extending.

**Comment by austinshenk** [comment]
I'm going to resolve this in favor of https://github.com/elm/compiler/issues/1897 since it explains the technical problem more clearly.
