### ISSUE TITLE
No error comments from a compiler when I give ONE argument to a function needs TWO as arguments.

### ISSUE THREAD

**Issue by thomasJs8** [elm/compiler#1992]
Hi, I'm new to Elm. I've found a weird return message on a console on the tutorial.
Tutorial page: https://guide.elm-lang.org/core_language.html

**Quick Summary** 
In the tutorial, there is a function "madlib" that needs two as arguments.
I gave one argument to it but the return is just "\<function>"

Let me show an example.

## Codes
Elm version depends on a console on the tutorial
```elm
-- here is the example you know.
> madlib animal adjective =
| "The ostantations " ++ animal ++ " wears " ++ adjective ++ " shorts."
| 
<function>

-- This is okay.
> madlib "cat" "ergonomic"
"The ostentatious cat wears ergonomic shorts."

-- This is an issue what I said
> madlib ("foo" ++ "bar")
<function>
```

## Conclusion
Is it not a problem?
If someone has already posted the same issue, I close this.

**Comment by Razzeee** [comment]
That's expected in functional programming languages that support currying.

It enables you to make you functions much more composable, but is sometimes quiet confusing to people coming from other languages.

**Comment by thomasJs8** [comment]
> That's expected in functional programming languages that support currying.

> It enables you to make you functions much more composable, but is sometimes quiet confusing to > people coming from other languages.

I see. I really appreciate it.
I just got confused about that haha.
