### ISSUE TITLE
Zip with Windows release

### ISSUE THREAD

**Issue by cup** [elm/compiler#1994]
i see here

https://github.com/elm/compiler/releases

that all releases are GZ, even Windows. This isnt a huge deal, as you can get tools to extract GZ on Windows. However to my knowledge they arent built in, even with Windows 10.

So it might make sense to offer ZIP builds instead to Windows users.

**Comment by evancz** [comment]
I recommend using the Windows installer if you want to install on Windows.

The `.gz` files are provided for the `npm` installer which is able to ungzip on any platform.

What is your scenario where you want to get the executable file directly in a third way?

**Comment by cup** [comment]
I posted this before I realized that its just a tool to make webapps

i prefer creating native programs

however i would still consider this a valid issue. Your framing is confusing though? I shouldnt have to explain or justify why ZIP should be used for Windows. Your response would be akin to me saying:

> Why do you want GZ files with Linux? We already offer ZIP support for Linux and thats good enough.

That might be true, but its not what Microsoft would do or say, and not what any number of other major Windows packages do.

**Comment by evancz** [comment]
I am curious why you'd like to install in a 3rd way. That helps me evaluate suggestions and prioritize work.

I'd expect people to install using the Windows installer, and I'd expect people with many different projects that use different versions to use the `npm` installer. The `.gz` links are primarily available for supporting other install paths, not for direct download.

**Comment by cup** [comment]
Looks like I was mistaken

https://devblogs.microsoft.com/commandline/tar-and-curl-come-to-windows
