### ISSUE TITLE
Cannot publish packages with Elm 0.19.1

### ISSUE THREAD

**Issue by jxxcarlson** [elm/compiler#1995]
**Cannot publish packages with Elm 0.19.1** 

## SSCCE

```
 $ elm publish
Verifying jxxcarlson/elm-markdown 3.0.0 ...

  ● Found README.md
  ● Found LICENSE
  ● Verified documentation
  ● Version number 3.0.0 verified (MAJOR change, 2.4.0 => 3.0.0)
  ● Version 3.0.0 is tagged on GitHub
  ● No uncommitted changes in local code
  ● Code downloaded successfully from GitHub
  ● Downloaded code compiles successfully

-- PROBLEM PUBLISHING PACKAGE --------------------------------------------------

I need to send information about your package to the package website, so I tried
to fetch:

    https://package.elm-lang.org/register?name=jxxcarlson%2Felm-markdown&version=3.0.0&commit-hash=0c444cfd1c7ba7783701530868e209e8930b2ce9

But it came back as 404 Not Found

This may mean some online endpoint changed in an unexpected way, so if does not
seem like something on your side is causing this (e.g. firewall) please report
this to https://github.com/elm/compiler/issues with your operating system, Elm
version, the command you ran, the terminal output, and any additional
information that can help others reproduce the error!

 $ git log | grep 0c444cfd1c7ba7783701530868e209e8930b2ce9
```

- **Elm:** 0.19.1
- **Browser:** N/A
- **Operating System:** Mac 10.4.4

## Additional Details

???

**Comment by zwilias** [comment]
When you create a tag in git, you have 2 options: a lightweight tag, or an annotated tag. When you create an annotated tag, the tag is not simply a name for a commit, but becomes its own object (with its own hash), that contains information such as the actual commit it is about.

https://api.github.com/repos/jxxcarlson/elm-markdown/git/tags/0c444cfd1c7ba7783701530868e209e8930b2ce9 for example, is the relevant 3.0.0 tag, with the ID as listed above, which points to bc19b6e028aa27ee40f645383510cf041b9a97d6 which does exist :)

There is an ongoing incident at Github - my guess is that this is the root cause for this issue.

I'd suggest trying again now or in a little while. If the publishing issue persist, please give an update!

**Comment by jxxcarlson** [comment]
Ok, thanks!  Its been that way for a day, but I'll just hang tight.

**Comment by jxxcarlson** [comment]
Still getting the same error after three days.

**Comment by evancz** [comment]
The compiler checks [this endpoint](https://api.github.com/repos/jxxcarlson/elm-markdown/git/refs/tags/3.0.0) when it tries to publish. It gives the following data:

```json
{
  "ref": "refs/tags/3.0.0",
  "node_id": "MDM6UmVmMjA0OTQzOTcwOjMuMC4w",
  "url": "https://api.github.com/repos/jxxcarlson/elm-markdown/git/refs/tags/3.0.0",
  "object": {
    "sha": "0c444cfd1c7ba7783701530868e209e8930b2ce9",
    "type": "tag",
    "url": "https://api.github.com/repos/jxxcarlson/elm-markdown/git/tags/0c444cfd1c7ba7783701530868e209e8930b2ce9"
  }
}
```

So it seems that it's something is corrupted in the GitHub data. You might try removing the `3.0.0` tag and adding it back again.

**Comment by jxxcarlson** [comment]
Oh my!  Tried removin the tag locally and remotely, then repeating the process.  Alas, the same result:

```
$ elm publish
Verifying jxxcarlson/elm-markdown 3.0.0 ...

  ● Found README.md
  ● Found LICENSE
  ● Verified documentation
  ● Version number 3.0.0 verified (MAJOR change, 2.4.0 => 3.0.0)
  ● Version 3.0.0 is tagged on GitHub
  ● No uncommitted changes in local code
  ● Code downloaded successfully from GitHub
  ● Downloaded code compiles successfully

-- PROBLEM PUBLISHING PACKAGE --------------------------------------------------

I need to send information about your package to the package website, so I tried
to fetch:

    https://package.elm-lang.org/register?name=jxxcarlson%2Felm-markdown&version=3.0.0&commit-hash=39cae131db6f974aebdbde27bcf47d9d30d517c9

But it came back as 404 Not Found

This may mean some online endpoint changed in an unexpected way, so if does not
seem like something on your side is causing this (e.g. firewall) please report
this to https://github.com/elm/compiler/issues with your operating system, Elm
version, the command you ran, the terminal output, and any additional
information that can help others reproduce the error!
```

**Comment by jxxcarlson** [comment]
PS.  As a sanity check, I cloned the repo, compiled and ran `./app-demo-fancy`. No errors.

**Comment by Zinggi** [comment]
I have the same problem.
Except that I'm trying to publish a new package, not an update to an existing one.
But I do get the same error:
```
I will now verify that everything is in order...

  ● Found README.md      
  ● Found LICENSE      
  ● Verified documentation    
  ● All packages start at version 1.0.0                  
  ● Version 1.0.0 is tagged on GitHub 
  ● No uncommitted changes in local code
  ● Code downloaded successfully from GitHub
  ● Downloaded code compiles successfully

-- PROBLEM PUBLISHING PACKAGE --------------------------------------------------

I need to send information about your package to the package website, so I tried
to fetch:

    https://package.elm-lang.org/register?name=Zinggi%2Felm-glsl-generator&version=1.0.0&commit-hash=1ded88491ee84c814eeeba0462a16a777d70ff52

But it came back as 404 Not Found

This may mean some online endpoint changed in an unexpected way, so if does not
seem like something on your side is causing this (e.g. firewall) please report
this to https://github.com/elm/compiler/issues with your operating system, Elm
version, the command you ran, the terminal output, and any additional
information that can help others reproduce the error!
```


I have tried to delete the tag and recreate it, but no luck.
I also tried creating a lightweight tag, but that also didn't work.

**Comment by jxxcarlson** [comment]
The problem continues. I've tried deleting the tag locally and remotely, dropping back to the previous version in `elm.json` and and doing the whole publishing process over again,  Alas, same result, e.g., today:

```
I need to send information about your package to the package website, so I tried
to fetch:

    https://package.elm-lang.org/register?name=jxxcarlson%2Felm-markdown&version=3.0.0&commit-hash=238fe93faa0c8deb00e1a38ce3c6b6c33d65fe49

But it came back as 404 Not Found
```

**Comment by aforemny** [comment]
Hi, I am experiencing what appears to be the same issue. Running `elm publish` on [this checkout](https://github.com/aforemny/material-components-web-elm/tree/v1.0.1) fails with

```
I need to send information about your package to the package website, so I tried
to fetch:

    https://package.elm-lang.org/register?name=aforemny%2Fmaterial-components-web-elm&version=1.0.1&commit-hash=8152ef788be657b4042db2f8caaac2390fb47216

But it came back as 404 Not Found
```

The [mentioned endpoint](https://api.github.com/repos/aforemny/material-components-web-elm/git/refs/tags/1.0.1) seems to return the [correct commit](https://api.github.com/repos/aforemny/material-components-web-elm/git/commits/8152ef788be657b4042db2f8caaac2390fb47216) which [seems to exists](https://github.com/aforemny/material-components-web-elm/commit/8152ef788be657b4042db2f8caaac2390fb47216).

**Comment by rl-king** [comment]
I'm running into the same issue. 

```Verifying driebit/elm-ginger 2.3.0 ...

  ● Found README.md      
  ● Found LICENSE      
  ● Verified documentation    
  ● Version number 2.3.0 verified (MINOR change, 2.2.1 => 2.3.0)
  ● Version 2.3.0 is tagged on GitHub 
  ● No uncommitted changes in local code
  ● Code downloaded successfully from GitHub
  ● Downloaded code compiles successfully

-- PROBLEM PUBLISHING PACKAGE --------------------------------------------------

I need to send information about your package to the package website, so I tried
to fetch:

    https://package.elm-lang.org/register?name=driebit%2Felm-ginger&version=2.3.0&commit-hash=79d36e8df330806ad6ac04d39184928de9c510cc

But it came back as 404 Not Found```

**Comment by evancz** [comment]
It may be something with the package website actually.

I will test some theories out, but I may need to reach out to one (or some) of you on Slack for certain experiments.

**Comment by evancz** [comment]
I believe it should be possible to publish with the 0.19.1 binaries now.

With the server changes, it was possible to publish the @jxxcarlson package. Can others in this thread try again to confirm in more cases?

* * *

The root cause appears to be that the following two lines of code do not have exactly the same meaning:

- 0.19.0 - https://github.com/elm/compiler/blob/0.19.0/builder/src/Deps/Website.hs#L337-L338
- 0.19.1 - https://github.com/elm/compiler/blob/0.19.1/terminal/src/Publish.hs#L396

I'm not 100% certain how https://github.com/elm/compiler/blob/0.19.1/builder/src/Http.hs#L242-L244 changes things, but that seems to be the origin of this.

The new server code now checks for both possible styles of upload, so it should keep working for 0.19.0 and 0.19.1 folks.

**Comment by jxxcarlson** [comment]
Working now. Thanks Evan!

**Comment by aforemny** [comment]
Works for me as well. Thanks!

**Comment by rl-king** [comment]
Works here as well, thanks!

**Comment by Zinggi** [comment]
Yup works now, thanks Evan for the quick fix!
