### ISSUE TITLE
The following Type is giving compile error

### ISSUE THREAD

**Issue by hariroshan** [elm/compiler#2000]
**Quick Summary:** I have a sum type, when added to Msg it gives me compilation error

## SSCCE

```elm
type Overlay
    = MovingAverage Int (Array Float)
    | BollingerBand

type Standalone
  = RSI
  | MACD

type Indicator
    = OverlayIndicator Overlay
    | StandaloneIndicator Standalone
type Msg =
    AddIndicator Indicator -- when i add this. it gives the following error

./src/elm/Main.elmError: Compiler process exited with error Compilation failedSuccess! Compiled 2 modules.
elm.exe: Map.!: given key is not an element in the mapCallStack (from HasCallStack):  
```

- **Elm:** 0.19.0
- **Browser:** Chrome 77.0.3865.120
- **Operating System:** Windows 10 pro

## Additional Details
Removing that message solves the compilation error. Are the Sum types Right?.

**Comment by Razzeee** [comment]
Please use 0.19.1 https://github.com/elm/compiler/releases/tag/0.19.1 as that should address the problem.

**Comment by hariroshan** [comment]
Thank you. @Razzeee . It did fix the issue. ☺️
