### ISSUE TITLE
"502 Bad Gateway" accessing package.elm-lang.org during elm init

### ISSUE THREAD

**Issue by lrvl** [elm/compiler#2002]
**Quick Summary:**

Today elm init can't download from package.elm-lang.org due 502 errors.

- **Elm:** 0.19.1
- **Browser:** Firefox 70
- **Operating System:** Microsoft Windows NT Windows 10.0.17763.0

## Additional Details

- Freshly installed on Win10 next to Visual Studio Code v1.39.2 (user setup / Electron 4.2.10)
- Checked using multiple ISP: Can't access the packages site

**Comment by HenkPoley** [comment]
Another remark, when package.elm-lang.org is down, and you try to build a elm.json with a package that is not cached on your machine, it will say:

```
>elm make
Dependencies ready!
-- TROUBLE VERIFYING DEPENDENCIES ------------------------------------- elm.json

I could not connect to https://package.elm-lang.org to get the latest list of
packages, and I was unable to verify your dependencies with the information I
have cached locally.

Are you able to connect to the internet? These dependencies may work once you
get access to the registry!

Note: If you changed your dependencies by hand, try to change them back! It is
much more reliable to add dependencies with elm install or the dependency
management tool in elm reactor.
```

Note that does _not_ say which dependency it was trying to fetch. 

For me specifically: This is kind of confusing a newcomer, when you *think* you already used _the_ json decoder, but this example that you are trying uses a _different_ json decoder that you haven't cached.

Overall it would be less confusing if it could simply say "these and these new dependencies I'm trying to fetch, but I can't".

**Comment by nunocf** [comment]
Experiencing the same. Our apps won't compile in CircleCI (or locally)

**Comment by the72nd** [comment]
Same issue.
502 error when trying to access https://package.elm-lang.org/all-packages

**Comment by Razzeee** [comment]
Should be working again

**Comment by lrvl** [comment]
Thanks for the quick response and solution
