### ISSUE TITLE
ERROR ON  yarn add elm@latest-0.19.1

### ISSUE THREAD

**Issue by pirovorster** [elm/compiler#2005]
I get a similar error both when I build my elm project OR when I call " yarn add elm@latest-0.19.1"

-- ERROR -----------------------------------------------------------------------

Something went wrong while fetching the following URL:

https://github.com/elm/compiler/releases/download/0.19.1/binary-for-windows-64-bit.gz

It is saying:

Error: connect ECONNREFUSED 127.0.0.1:443

**Comment by evancz** [comment]
I cannot reproduce this. On macOS 10.15 the command `yarn add elm@latest-0.19.1` works with no problem.

Is it possible that you have a company firewall? Something that would block requests to github from terminal commands?

Please share information about your OS. If you are running this on a work computer, do you get the same error running on a network outside of work? Etc.

**Comment by pirovorster** [comment]
@evancz thanks for the quick response. I eventually figured out that it was my dns that was acting up. I switched to the google dns and now all seems better. Sorry for the false issue. Keep up the good work.
