### ISSUE TITLE
Updating the Compiler using the compile

### ISSUE THREAD

**Issue by CSDUMMI** [elm/compiler#2009]
**Quick Summary:** 
Many package managers have an option 
to update themselves:
```bash
$ npm install npm -g
```
I did have this problem, 
because I don't want to reinstall
elm, every time there is a third digit update.
My proposal is thus self-evident:
## SSCCE

```bash
$ elm install elm
```

**Why don't you just use npm to update elm?**
Either `elm` either is an independent package manager, which can be installed separately, or it is a dependency to a project using the npm package manager.
Because you can and are recommend to install elm as an independent 
compiler and package manager, I think this feature should be included in elm.

**Comment by evancz** [comment]
We have talked about having Elm be able to get the appropriate executable based on the version mentioned in `elm.json`, so I think this is a variant of that overall idea. Not sure when we'd work on that, but it's a known idea.

We generally do not track feature requests or design ideas in issues. They can end up sitting around for a long time and make it harder to understand and fix reports of potential bugs.
