### ISSUE TITLE
Compiling for ARM64

### ISSUE THREAD

**Issue by CSDUMMI** [elm/compiler#2010]
**Quick Summary:** ???
I tried to use Elm on a ARM64 based RPi 4, 
but I couldn't find a binary for that CPU Instruction set.
Is there a problem with the elm compiler, that would make it impossible
to provide such a binary? 

- **Elm:** 0.19.1
- **Browser:** Whatever
- **Operating System:** Linux Raspbian for ARM64

## Additional Details
Raspbian is Debian based and it thus must be an issue with the ARM64 instruction set.

**Comment by evancz** [comment]
The compiler is written in Haskell, and we create three binaries for each release.

One for Mac, Linux, and Windows and all are 64-bit binaries.

It is possible to build for other platforms using the steps [here](https://github.com/elm/compiler/blob/master/installers/linux/Dockerfile), but we do not do that at this time. We are gathering information on who might want binaries for more platforms to assess the cost/benefit of doing that.

So I will close this issue, log it in #2007, and any further information should be added in this thread.

To help assess this, can you tell us more about your project? What are you hoping to do with Elm on a Rasberry Pi?

**Comment by rlefevre** [comment]
@CSDUMMI 

For now, you can try the unofficial and experimental binaries provided here:
https://github.com/dmy/elm-raspberry-pi

**Comment by asianfilm** [comment]
One use case is for writing and compiling Elm code when offline on an iPad Pro with a Raspberry Pi attached (and networked to the iPad) over the USB-C cable. This does not requiring jailbreaking of the iPad.

There are several recent YouTube videos of how to set this up for other languages, such as [this one](https://m.youtube.com/watch?v=IR6sDcKo3V8), which also has a follow-up video answering detailed questions.

I’m on an older iPad and haven’t been able to try this.

**Comment by bburdette** [comment]
I've got my eye on the pinebook pro for a high battery life dev machine for use on trips and so forth.  Its an arm64 laptop with 4g ram for just 200$.  If I get one I'll look into compiling elm for it, if binaries aren't around by then.

**Comment by asonix** [comment]
I'd be interested in elm for pinebook pro. I'm currently typing this from a pinebook pro and have been trying to find anything precompiled. I'll try out the raspberry pi version and report back

**Comment by whatevergeek** [comment]
i was trying to install elm on arm64 (ubuntu OS via userland on an Android phone). I generally do this when developing on the go. Sadly, elm doesn't run on it. Hope to find an elm cli binary i can install... will try to check the building stuff if i get some time...

**Comment by whatevergeek** [comment]
> i was trying to install elm on arm64 (ubuntu OS via userland on an Android phone). I generally do this when developing on the go. Sadly, elm doesn't run on it. Hope to find an elm cli binary i can install... will try to check the building stuff if i get some time...

ah... looks like there's another ticket raised for this: https://github.com/elm/compiler/issues/2117

I'll track from there :-)
