### ISSUE TITLE
Benchmarks against Marko and Vue?

### ISSUE THREAD

**Issue by basickarl** [elm/compiler#2016]
Was reading on your website about benchmarks but didn't see anything regarding benchmarks against Marko and Vue?

You guys include Vue under **Small Assets** but not **Great Performance**. I get the feeling you guys are selecting what you want to show due to not wanting to look slower?

**Comment by rlefevre** [comment]
Performance benchmarks are from 2016, but assets ones from 2018 (check the blogs dates).
In 2016, Vue was not that popular, that's all.

Benchmarking takes a lot of time, as an Elm user, I don't really expect them to be updated each year for each new popular framework.

**Comment by basickarl** [comment]
@rlefevre well could it be updated to include those years, as I mentioned it makes it look as though elm is trying to hide numbers.

**Comment by evancz** [comment]
I think the benchmark comparisons done [here](https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html) are quite thorough. Their testing covers the cases that would really distinguish one implementation from another in a practical setting.

Here are some of the results from the projects you mention:

![Screen Shot 2019-11-14 at 9 35 13 AM](https://user-images.githubusercontent.com/1658058/68866235-1725d980-06c2-11ea-81c9-360bf28ec98f.png)

Nothing to hide.

If you check out the site they run, it would be extraordinarily difficult to maintain this level of comparison ourselves. I have never heard of "Marko" before today, but it's in the comparison there already. It's not clear how to have the old post match the thoroughness of this project.
