### ISSUE TITLE
Homebrew bottle version

### ISSUE THREAD

**Issue by wonbyte** [elm/compiler#2025]
**Quick Summary:** When I install elm via homebrew i get the elm-0.19.0.mojave.bottle.tar.gz version. Is this ok to run on macOS Catalina? I have tried the repl and everything seems to work fine so just want to make sure.

- **Elm:** 0.19.0
- **Operating System:** macOS Catalina

**Comment by evancz** [comment]
I'm not sure who creates the Homebrew distribution for Elm.

I know that if you use the mac installer from [here](https://guide.elm-lang.org/install/elm.html) all it does is place a file at `/usr/local/bin/elm`. You can also just get the executable file directly from [here](https://github.com/elm/compiler/releases/tag/0.19.1). All it will ever do to your system is put things in `~/.elm/`, so it's pretty easy to clean up either way.

Not sure who to talk to about homebrew things though!

**Comment by Razzeee** [comment]
I guess it's waiting for https://github.com/Homebrew/homebrew-core/pull/46387
