### ISSUE TITLE
Bad amount of spaces in error reporting for NAME CLASH

### ISSUE THREAD

**Issue by Janiczek** [elm/compiler#2037]
**Quick Summary:** `fn arg {arg} = arg` has the first red squiggle in a wrong place

## SSCCE

https://ellie-app.com/7vMDwMWwSFna1
```elm
fn arg {arg} = arg
```

- **Elm:** 0.19.1
- **Browser:** non-applicable
- **Operating System:** Linux 64bit

## Additional Details

When I found the bug, the red squiggles were not at the beginning of the next line but ~65k chars away (!), which suggests some underflow. It is a private code and I wasn't able to make a SSCCE for this particular underflow yet. I can give it another try if you'll want it.

The code looked something like this:
```elm
config =
  foo
    { some = 1
    , fields = 2
    , thisOne =
        \currentSize { currentBasesCount, currentSize, totalLimit } ->
            ...
    }
```
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/149425/70934847-27253600-203f-11ea-8617-a1e2e51feca3.gif)

**Comment by Janiczek** [comment]
Another way to trigger this:
```elm
case ( foo1, foo2 ) of
    ( Start bar, End bar ) -> -- these two `bar`s throw Elm compiler off
        baz
```

**Comment by evancz** [comment]
With the changes in https://github.com/elm/compiler/commit/8a4b62e08ed6da54dbed326229435b1f7becea53 I am seeing the following:

```
-- NAME CLASH --------------------------------------------------------- test.elm

This anonymous function has multiple `currentSize` arguments.

17|       \currentSize { currentBasesCount, currentSize, totalLimit } ->
           ^^^^^^^^^^^                      ^^^^^^^^^^^
How can I know which one you want? Rename one of them!

-- NAME CLASH --------------------------------------------------------- test.elm

This `case` pattern has multiple `bar` variables.

9|     ( Start bar, End bar ) -> -- these two `bar`s throw Elm compiler off
               ^^^      ^^^
How can I know which one you want? Rename one of them!

-- NAME CLASH --------------------------------------------------------- test.elm

The `fn` function has multiple `arg` arguments.

2| fn {arg,arg} = arg
       ^^^ ^^^
How can I know which one you want? Rename one of them!
```

Thank you for the report!

**Comment by Janiczek** [comment]
From the diff it looks like that might have been a tricky fix! Thanks for fixing :heart:
