### ISSUE TITLE
npm install elm will fail on win32 arch

### ISSUE THREAD

**Issue by korutx** [elm/compiler#2038]
**Quick Summary:** `npm i -g elm` will fail on `process.arch = 'ia32'`

## SSCCE

The url produced by download script for node win32 arch is 
[https://github.com/elm/compiler/releases/download/0.19.1/binary-for-windows-32-bit.gz](https://github.com/elm/compiler/releases/download/0.19.1/binary-for-windows-32-bit.gz) but there is not such resource available

```js
//file: installers/npm/download.js:21
var arch = { 'x64': '64-bit', 'ia32': '32-bit' }[process.arch];
var url = 'https://github.com/elm/compiler/releases/download/' + version + '/binary-for-' + os + '-' + arch + '.gz';
```
- **Elm:** 0.19.1
- **Browser:** non-applicable
- **Operating System:** Windows 10

## Additional Details

Some applications like create-elm-app rely on that mode for installing elm.

**Comment by evancz** [comment]
Thank you for the report.

We are currently only building 64-bit binaries, so that is what is available through the installer and through npm.

Can you add more details as to why you need `ia32` to work? I am not familiar with the particulars of create-elm-app that are relevant to this. Once we have that info, I can add a note to #2007 which will help us evaluate if more official binaries should be built.

**Comment by korutx** [comment]
Right now it is not a big deal for us. We were trying to integrate elm with other tools souch as nodegit, that way, me and my team can share a common set of tools for developing. It was not clear for us that Elm only distributes a 64-bit binary. We often install Elm alongside with others nodejs tools, so is natural to use the elm's npm install option. Sometimes node is installed in 32-bits on Windows. There are many reasons for that:
1. Windows machines running under 32-bits
2. The need of installing nodejs 32-bits due to some native modules that just work on 32-bits architecture.
3. Multi enviroment scenarios throught nvm

Finally, we understood that we should use elm  64-bits if we want to integrate it on our tools' stack 

Thanks!
