### ISSUE TITLE
Typo: are you are

### ISSUE THREAD

**Issue by dptole** [elm/compiler#2046]
**Quick Summary:** Typo

https://github.com/elm/compiler/blob/master/compiler/src/Reporting/Error/Canonicalize.hs#L680-L691

https://github.com/elm/compiler/blob/master/compiler/src/Reporting/Error/Canonicalize.hs#L726-L737

"Are you **are** trying to mutate a variable?"

## SSCCE

```elm

```

- **Elm:** ???
- **Browser:** ???
- **Operating System:** ???

## Additional Details

???

**Comment by evancz** [comment]
Thank you for the report! The fix should be available in the next release of Elm.
