### ISSUE TITLE
Namespaces?

### ISSUE THREAD

**Issue by Darker7** [elm/compiler#2047]
I was looking for a way to create namespaces in Elm but neither the guide, nor DuckDuckGo told me anything about them. And when I came here to look for an issue about them I found neither an open, nor closed one.  
So I was wondering whether I missed something obvious; is there somewhere a statement on why Elm doesn't do namespaces? or maybe Elm does do namespaces and I've just missed it somehow? or maybe you're planning on implementing them and I've just searched in the wrong places?  
  
I've already cooked about a whole proposal for namespaces in my head but I figured it'd be better to ask the above before busting down the door with it :Ü™

**Comment by rlefevre** [comment]
What is needed is a way to avoid the rare but existing modules conflicts.
See https://github.com/elm/compiler/issues/1625 for the meta issue.

**Comment by Darker7** [comment]
Hmm, the proposal for namespaces I've cooked up is completely from scratch. I'll look through the links provided tomorrow morning after I've got a good nights sleep then and probably post my proposal :Ü™
