### ISSUE TITLE
Proposal: Namespaces

### ISSUE THREAD

**Issue by Darker7** [elm/compiler#2048]
# Preamble

Currently Elm has two levels of namespaces: modules and packages. The former of which is impossible to nest and the latter a tool outside of the code itself.  

# The benefits of namespaces

Namespaces enable the reuse of names – which simplifies naming by removing the necessity of overly verbose names to avoid naming collisions – and grouping of code spread across multiple files into one architectural unit – which is useful for human readability.

# The proposal
## Declaring namespaces

```Elm
namespace A.Alpha.Utils with
module Helper exposing (..)
.
.
```
I propose that namespaces:
- contain only modules and namespaces.
- be implicitly declared, as such the compiler will have to detect possible misspellings. 
- also be used as file namespaces i.e. directories:
```
src +
    |- A +
    |    |- Alpha +
    |    |        |- App +
    |    |        |      |- Eval.elm
    |    |        |      |- Print.elm
    |    |        |      \- Read.elm
    |    |        \- Utils +
    |    |                 |- Helper.elm
    |    |                 \- Wrapper.elm
    |    \- Beta +
    |- B +
    |    |- Alpha +
    |    |- Beta +
    |    |- Master.elm
    |    \- Slave.elm
.
.
```

## Importing namespaces

I propose that the import syntax should be the same as for modules with some additions to account for their greater capability.
```Elm
.
.
import A.Alpha.Utils.Helper as Helper exposing (..)
import A.Alpha.App as App exposing (Read exposing (..), Eval)
import A.Alpha
import B exposing (..)
.
.
```
Let's go through the list of examples one by one.  
- The first import statement is importing `src/A/Alpha/Utils/Helper.elm` with all of its functions and constants available as unqualified imports.  
- The second statement is importing all modules contained in `src/A/Alpha/App/` with qualified alias App and exposes the Read and Eval modules as unqualified imports with Read further exposing all of its content.  
- The third statement is importing all namespaces contained in `src/A/Alpha/` as qualified imports and as such must all be prefaced with `A.Alpha`.  
Example: `A.Alpha.Utils.Wrapper.functionOne x`  
- The fourth statement is importing all namespaces and modules contained in `src/B/` as unqualified imports.  
Example: `Master.drive (Slave.newWith Slave.Id 1413)`

## Avoiding collisions

In my probing questions (#2047) a day ago I was made aware of the problem with namespace collisions (#1625).

On the module level all collisions between modules and namespaces will be introduced by the user and as such will have to be resolved by the user. As namespaces are a new element and not a change their introduction will cause no collisions because no namespaces will exist at that point in time.

On the package level my proposal adds **no** new collision opportunities to the issue because the implicit declaration will automatically merge identically named namespaces originating from two packages. However the old problem of conflicting module names will still be present. <sup>If one import has a module with the same name as a namespace from another that is equivalent to two modules having the same name.</sup> :Ü™

**Comment by layflags** [comment]
Not sure what you mean, but why do you not just use `module A.Alpha.Utils.Helper exposing (..)` and put the file into the respective directory structure? That's works out of the box with Elm.

**Comment by Darker7** [comment]
What happens if I tell Elm `import A`? It's going to give me an error "module not found" :Ü™

**Comment by layflags** [comment]
> What happens if I tell Elm `import A`? It's going to give me an error "module not found" :Ü™

When there's no `A.elm` file in your `src` folder top level you are right.

**Comment by evancz** [comment]
We generally try to track specific bugs in issues, and have discussions about proposals in https://discourse.elm-lang.org/ where more people will see it and give feedback.

I have been using Haskell for about a decade now, and have never felt like something like this was missing, but perhaps folks on discourse will reveal other perspectives. So further discussion should happen there.
