### ISSUE TITLE
Is `Extensible a` a subset of `a`

### ISSUE THREAD

**Issue by choonkeat** [elm/compiler#2071]
**Quick Summary:** In places where I need `a` but I have extensible record of `a`, compiler should consider it ok

## SSCCE

```elm
module Main exposing (..)


type alias Named a =
    { a | name : String }


unwrap : Named a -> a
unwrap recordWithName =
    recordWithName
```

- **Elm:** 0.19.1
- **Browser:** N/A
- **Operating System:** macOS Catalina

UPDATE: I renamed the function argument to `recordWithName` to avoid repeating `a` from type signature

**Comment by rlefevre** [comment]
`a` in `unwrap a = ` is a `Named a`, it is not a `a` from the signature.

This is the same as saying that the compiler should consider ok to have:
```elm
n : a
n = 42
```
This is not how it works.
`n` cannot return any type, it can only return a `number`, and `unwrap` cannot return any type, it can only return a `Named a`, which is a `{ a | name : String }`, which is not any type.

**Comment by folkertdev** [comment]
I think this is clearer without the alias. `{ a | name : String }` is **not** any record `a` with additionally the field `name` of type `String`." Rather it is "any record type `a` that has a `name` field of type `String`."

Therefore
```
unwrap : { a | name : String } -> a
unwrap a = a
```

is similar to saying 

```
unwrap : { foo : Int, name : String } -> { foo : Int }
unwrap r = r
```

This is not allowed in elm's type system.

**Comment by jacobkolind** [comment]
I believe what @choonkeat is saying, is that the type of an instance of `Named a` and the type of an instance of `a` should be one and the same type, provided that `a` is a record type with a field called `name`.

In certain cases that holds true:
```
> type alias NameAndId = { id : String, name : String }
> type alias Named a = { a | name : String }
> x : Named NameAndId
| x = { id = "id", name = "name" }
|
{ id = "id", name = "name" }
    : Named NameAndId
> y : NameAndId
| y = { id = "id", name = "name" }
|
{ id = "id", name = "name" } : NameAndId
> x == y
True : Bool
```
The compiler allows us to compare `x` and `y` - thus they must be of the same type, although the type signature of `x` and `y` printed by the REPL are different.

In other instances they are not the same type:
```
> type Msg a = WrapNamed (Named a)
> u = WrapNamed x
WrapNamed { id = "id", name = "name" }
    : Msg NameAndId
> v = WrapNamed y
WrapNamed { id = "id", name = "name" }
    : Msg { id : String }
> u == v
-- TYPE MISMATCH ---------------------------------------------------------- REPL

I need both sides of (==) to be the same type:

14|   u == v
      ^^^^^^
The left side of (==) is:

    Msg NameAndId

But the right side is:

    Msg { id : String }

Different types can never be equal though! Which side is messed up?

Hint: Seems like a record field typo. Maybe name should be id?

Hint: Can more type annotations be added? Type annotations always help me give
more specific messages, and I think they could help a lot in this case!
```
The REPL recognises that both `u` and `v` contains the same data - `WrapNamed { id = "id", name = "name" }` - but claims that the types are different, which they clearly aren't.

**Comment by choonkeat** [comment]
> Therefore
> ``` elm
> unwrap : { a | name : String } -> a
> ```
> is similar to saying
> ``` elm
> unwrap : { foo : Int, name : String } -> { foo : Int }
> ```

the return type is incorrectly translated: type `a` in `{ a | name : String }` must contain `name : String` as you've explained too

> any record type `a` that has a `name` field of type `String`

so the similar code sample should've been

```elm
unwrap : { foo : Int, name : String } -> { foo : Int, name : String }
```

**Comment by choonkeat** [comment]
i think i understand now

``` elm
unwrap : { a | name : String } -> a
unwrap arg = 
```

parameter `arg` is effectively only `{ name : String }`, so the "similar code" expansion (if we had passed in a `{ foo : Int, name : String }` value as `arg`, should actually be

``` elm
unwrap : { name : String } -> { foo : Int, name : String }
unwrap arg = arg
```

and that's not allowed
