### ISSUE TITLE
Lists of fixed length

### ISSUE THREAD

**Issue by ennmichael** [elm/compiler#2074]
This is intended as a friendly question on the design of Elm. I understand the reasoning behind why tuples must have fewer than four items. However, this reduces their usefulness, because now I can't enforce "lists" of fixed length. For example, imagine I measure the temperature four times a day (for some specific reason). In Elm, I thought I could represent this data like this:
```elm
measurements = (10, 13, 12, 20)
```
However, I find out that this is not the case, and the compiler is telling me to use a record instead. Now I have two options: either introduce this silly record
```elm
type alias Measurements = { t1 : Int, t2 : Int, t3 : Int, t4 : Int }
```
or use a list, but now my API accepts input that I might not be ready to handle, and `Maybe` types abound. Is there a better alternative that I am missing?

Perhaps the example is not the most compelling possible, but I expect people might want to represent list-like data of fixed length larger than three.

**Comment by ennmichael** [comment]
Perhaps (and perhaps not) it might be a good idea to allow tuples larger than three if all the element types are the same.

**Comment by Razzeee** [comment]
Sorry, but the only reason your record is `silly` is due to you not spending time on good names. I know naming is hard :)
```
type alias Measurements = {  at8: Int, at12 : Int, at16 : Int, at20 : Int }
```
It offers anyone else way more information as your tuple example. Everybody would need to read way more code to be able to understand what your doing, or which tuple is which.

**Comment by Neppord** [comment]
You may also nest tuples if what you want is a rigid structure.

```elm
measurements = ((10, 13, 12), 20)
```

**Comment by rlefevre** [comment]
Another option is to use a custom type:
```
type Measurements = Measurements Int Int Int Int
```
So you can pattern match the values directly:
```
case measurement of 
    (Measurements 0 0 0 0) -> ...
    (Measurements m1 m2 m3 m4) -> ...
```
```
t1 : Measurements -> Int
t1 (Measurements m1 _ _ _) =
     m1
```

You could also make a Tuple4 type this way:
```
type Tuple4 a b c d
    = Tuple4 a b c d


first : Tuple4 a b c d -> a
first (Tuple4 a _ _ _) =
    a


second : Tuple4 a b c d -> b
second (Tuple4 _ b _ _) =
    b


third : Tuple4 a b c d -> c
third (Tuple4 _ _ c _) =
    c


fourth : Tuple4 a b c d -> d
fourth (Tuple4 _ _ _ d) =
    d


mapFirst : (a1 -> a2) -> Tuple4 a1 b c d -> Tuple4 a2 b c d
mapFirst f (Tuple4 a b c d) =
    Tuple4 (f a) b c d

-- ...
```
I think a record is better though.

**Comment by lue-bird** [comment]
There's also [typesafe-array](https://package.elm-lang.org/packages/lue-bird/elm-typesafe-array/latest/) and [static-array](https://package.elm-lang.org/packages/Orasund/elm-static-array/latest/) now.
