### ISSUE TITLE
Compiler trying to write in its install dir does not play nice with containers

### ISSUE THREAD

**Issue by radoye** [elm/compiler#2080]
**Quick Summary:** 

Can `elm` compiler put temporary files in `$HOME` instead of the `elm install dir`?

We use Singularity containers for development. All compilers are under `/opt/dev/` which is mounted read-only for users. Elm compiler makes an unusual choice to try writing in its install directory, `/opt/dev/elm/` in our case. A more common solution would be to write into `~/.elm/`. Can this be changed?

```bash
Singularity> which elm
/opt/dev/elm/elm
Singularity> elm make src/Main.elm 
elm: /opt/dev/elm/0.19.1: createDirectory: permission denied (Read-only file system)
Singularity> mkdir -p ~/.elm/0.19.1
Singularity> ls -al ~/.elm/0.19.1/
total 8
drwxr-xr-x 2 rrs rrs 4096 Apr  7 16:18 .
drwxr-xr-x 3 rrs rrs 4096 Apr  7 16:18 ..
Singularity> 
```

- **Elm:** 0.19.1
- **Browser:** N/A 
- **Operating System:** Ubuntu 18.04

**Comment by rlefevre** [comment]
This is unexpected. Maybe you have the `ELM_HOME` environment variable set to `/opt/dev/elm` as this defines the elm directory to which it caches packages (not temporary files, which are written to `./elm-stuff`).

Can you check with `echo $ELM_HOME`?

**Comment by radoye** [comment]
@rlefevre Indeed, you are right. Our `echo $ELM_HOME` produces `/opt/dev/elm`. To confirm, should we just put `export ELM_HOME=$HOME` during container startup?

**Comment by rlefevre** [comment]
@radoye You can just unset it (`unset ELM_HOME`), by default `elm` will use `$HOME/.elm`.
But it would probably be better to find where it is set in your container and remove this configuration which does not come from `elm`.
