### ISSUE TITLE
`List (Maybe a)` should fullfill `List (Maybe (List a))`

### ISSUE THREAD

**Issue by Neppord** [elm/compiler#2086]
**Quick Summary:**
 I expect functions that has the type `List (Maybe a) -> Maybe (List a)` to be able to handle when `a` is of type `List b`, i.e. match the signature of `List (Maybe (List a)) -> Maybe (List (List a))` 

## SSCCE
Here I need to duplicate the body of flip that changes a `List` of `Maybe` to a `Maybe` of `List` since the type engine don't realize it can make flip more specific.
```elm
module Matrix exposing (..)
type alias Matrix x =
    List (List x)

rows : Matrix a -> List (List a)
rows matrix =
    let
        flip : List (Maybe a) -> Maybe (List a)
        flip =
            List.foldr (Maybe.map2 (::)) (Just [])

        -- this should not be needed
        flipSpecific : List (Maybe (List a)) -> Maybe (List (List a))
        flipSpecific =
            List.foldr (Maybe.map2 (::)) (Just [])

        head : Matrix a -> Maybe (List a)
        head m =
            flip (List.map List.head m)

        tail : List (List a) -> Maybe (List (List a))
        tail m =
            flipSpecific (List.map List.tail m)
    in
    case ( head matrix, tail matrix ) of
        ( Nothing, _ ) ->
            []

        ( Just row, Nothing ) ->
            row :: []

        ( Just row, Just m ) ->
            row :: rows m
```

The compiler gives this error if we use `flip` in place of `flipSpecific`, which is not wrong but should not be needed.

> Detected problems in 1 module.
> -- TYPE MISMATCH ------------------------------------------------ src\Matrix.elm
> 
> Something is off with the body of the `tail` definition:
> 
> 23|             flip (List.map List.tail m)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
> This `flip` call produces:
> 
>     Maybe (List a)
> 
> But the type annotation on `tail` says it should be:
> 
>     Maybe (List (List a))
> 
> -- TYPE MISMATCH ------------------------------------------------ src\Matrix.elm
> 
> The 1st argument to `flip` is not what I expect:
> 
> 23|             flip (List.map List.tail m)
>                       ^^^^^^^^^^^^^^^^^^^^
> This `map` call produces:
> 
>     List (Maybe (List a))
> 
> But `flip` needs the 1st argument to be:
> 
>     List (Maybe a)
> 
> Hint: Your type annotation uses type variable `a` which means ANY type of value
> can flow through, but your code is saying it specifically wants a `List` value.
> Maybe change your type annotation to be more specific? Maybe change the code to
> be more general?
> 
> Read <https://elm-lang.org/0.19.1/type-annotations> for more advice!
> 

- **Elm:** 0.19.1
- **Browser:** compiler
- **Operating System:** windows

## Additional Details

Hope this is not a duplicate issue, I tried to find one but did not know what to search for.

**Comment by zwilias** [comment]
Hi @Neppord 

In Elm, using `a` in type signatures in `let .. in` declarations of functions that use `a` in their type signatures, means you're referring to the same type. In order to make your `flip` generic and only declare it once, you can use an unbound type variable instead, for example, `b`:

```elm
rows : Matrix a -> List (List a)
rows matrix =
    let
        flip : List (Maybe b) -> Maybe (List b)
        flip =
            List.foldr (Maybe.map2 (::)) (Just [])

        head : Matrix a -> Maybe (List a)
        head m =
            flip (List.map List.head m)

        tail : List (List a) -> Maybe (List (List a))
        tail m =
            flip (List.map List.tail m)
    in
    case ( head matrix, tail matrix ) of
        ( Nothing, _ ) ->
            []

        ( Just row, Nothing ) ->
            row :: []

        ( Just row, Just m ) ->
            row :: rows m
```

This behaviour makes it possible to write code like this:

```elm
foo : a -> a
foo x =
    let
        y : a
        y =
            x
    in
    y
```

where the type of `y` will be known to the compiler to be the same as that of `x`, so mostly useful for value declarations in `let .. in` context where you don't pass through the variable with the type variable.

In your case, this means you could rewrite to the following equivalent code:

```elm
rows : Matrix a -> List (List a)
rows matrix =
    let
        flip : List (Maybe b) -> Maybe (List b)
        flip =
            List.foldr (Maybe.map2 (::)) (Just [])

        head : Maybe (List a) -- Refers to the same `a` as the surrounding context!
        head =
            flip (List.map List.head matrix)

        tail : Maybe (List (List a)) -- Refers to the same `a` as the surrounding context!
        tail =
            flip (List.map List.tail matrix)
    in
    case ( head, tail ) of
        ( Nothing, _ ) ->
            []

        ( Just row, Nothing ) ->
            row :: []

        ( Just row, Just m ) ->
            row :: rows m
```

**Comment by Neppord** [comment]
Thank you! This explains why it doesn't work.

So then it's not a bug, it's a feature. The error message could be improved.
