### ISSUE TITLE
Request 0.18 binary for Linux 32-bit

### ISSUE THREAD

**Issue by MarkDBlackwell** [elm/compiler#2089]
Please restore the 32-bit Linux binary of version 0.18.0 to the [releases](https://github.com/elm/compiler/releases) page.

I found installing 0.18.0 via npm to be more complicated and difficult.

With 0.18.0, I'm merely touching-up an old project. Some others may be doing the same.

**Comment by rlefevre** [comment]
The old releases are here:
https://github.com/elm-lang/elm-platform/releases
