### ISSUE TITLE
List of shared libraries Elm is linked to

### ISSUE THREAD

**Issue by aminnairi** [elm/compiler#2096]
**Quick Summary:** Question about the list of shared libraries that Elm is using to build a minimal Docker image on top of the Elm executable.

- **Elm:** `0.19.1`
- **Docker Image:** `busybox:glibc`

## Additional Details

I am trying to create a Docker image for using the Elm executable in a portable way.

```console
$ docker run aminnairi/elm elm init
```

In my quest to reduce the image size to the maximum possible, I have found the use of the `busybox:glibc` image quite useful since it is only 2 megabytes and I have successfully managed to do something similar with the Deno interpreter [here](https://github.com/aminnairi/deno/blob/latest/docker/Dockerfile) using multi-stage building.

When I managed to successfully retrieve all libraries used by Deno and include them in the next stage, I didn't managed to do the same for Elm (even though I loved how the interpreter didn't just crash). The interpreter gave me a message like:

```
elm init
Hello! Elm projects always start with an elm.json file. I can create them!

Now you may be wondering, what will be in this file? How do I add Elm files to
my project? How do I see it in the browser? How will my code grow? Do I need
more directories? What about tests? Etc.

Check out <https://elm-lang.org/0.19.1/init> for all the answers!

Knowing all that, would you like me to create an elm.json file now? [Y/n]: y
-- PROBLEM LOADING PACKAGE LIST ------------------------------------------------

I need the list of published packages before I can start initializing projects,
so I tried to fetch:

    https://package.elm-lang.org/all-packages

But my HTTP library is giving me the following error message:

    InternalException (HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa)))

Are you somewhere with a slow internet connection? Or no internet? Does the link
I am trying to fetch work in your browser? Maybe the site is down? Does your
internet connection have a firewall that blocks certain domains? It is usually
something like that!
```

I know that my connection is OK and that I am not behind a proxy. The problem must certainly be that the Elm interpreter is linked over some shared library (just like Deno, see link to the Dockerfile above).

After all that context setting, my question is: where can I get a list of all shared libraries that Elm is relying on? It would be very useful for me to use `busybox:glibc` for my next stage.

Thanks for your answers!

**Comment by rlefevre** [comment]
Try to install the certificate packages in your Docker container.
The package is often called "ca-certificates".

Note that the Linux `elm` binary is already portable, as it is completely statically linked.

**Comment by aminnairi** [comment]
Hi @rlefevre and thank you for your answer.

> You are missing some CA certificates, not some shared library.

I see you are right I didn't install the `ca-certificates` just like I did with Deno. That was a mistake...

> Note that the Linux elm binary requires no shared library at all, as it is completely statically linked.
It should run on a barebones kernel so you could just add it to an Alpine Linux container...

Oh I didn't know that! That's so cool to hear. Thanks for your suggestion, I'll use Alpine for the build stage as you suggested.

I have now managed to resolve this issue by looking at what the [`ca-certificates`](https://manpages.ubuntu.com/manpages/xenial/man8/update-ca-certificates.8.html) package does (which I didn't know, creates a bunch of files).

I have successfully copied the files into my final stage, which is using Busybox, and now HTTP requests are working as intended! :tada:

I guess I'll close this issue for now since my issue is solved. Thanks again for your help and details, it is really appreciated!
