### ISSUE TITLE
Compiler error: Recieving a SIGILL when running elm executable

### ISSUE THREAD

**Issue by MonAaraj** [elm/compiler#2140]
**Quick Summary:** After following the [linux installation instructions](https://github.com/elm/compiler/blob/master/installers/linux/README.md), trying to run the executable produces this error message: `fish: 'sudo ./elm' terminated by signal SIGILL (Illegal instruction)`

## SSCCE
Follow the earlier linked instructions, then try to run the file.

- **Elm:** 0.19.1
- **Operating System:** Ubuntu 19.10 aarch64

## Additional Details

Using the fish shell, I have a machine that runs on arm64 which I believe might be the reason?

**Comment by lydell** [comment]
Here are two issues about arm: https://github.com/elm/compiler/issues/2007 and https://github.com/elm/compiler/issues/2117

As you can see in https://github.com/elm/compiler/issues/2007, use cases for more binaries are gathered. So I think more information about why run on arm etc would be appreciated! (Note: I’m not a maintainer, just trying to help out a little :) I know next to nothing about arm.)

Btw, you shouldn’t need to run `elm` with `sudo`.

**Comment by MonAaraj** [comment]
Thank you.

**Comment by lydell** [comment]
If you would like to see arm support in the future, then write down your use case here like this: https://github.com/elm/compiler/issues/2141

And reopen the issue. Then Evan can go through issues in a [batch](https://github.com/elm/expectations/blob/master/batching.md) and add them to #2007.
