### ISSUE TITLE
npm istall on macOS Big Sur can't finish

### ISSUE THREAD

**Issue by maxfarseer** [elm/compiler#2158]
**Quick Summary:**
I'm trying to run `npm install elm` but the process is frozen on `download elm` step.
![Screenshot 2020-12-16 at 09 38 24](https://user-images.githubusercontent.com/1026825/102331342-06155f00-3f8b-11eb-8887-c721558a5459.png)
Nothing happens after this.

- **Elm:** 0.19.x
- **Operating System:** macOS Big Sur (11.0.1)
- **Node version:** `v12.18.3` and `v14.15.2`
- **Macbook version:** Macbook Pro 15" 2017

**Comment by lydell** [comment]
Related: https://github.com/elm/compiler/pull/2156

**Comment by maxfarseer** [comment]
@lydell hello! I have a macbook pro 15 2017, it's not M1. Still related?

**Comment by lydell** [comment]
Ooops! Sorry. Maybe not.

**Comment by brightly-salty** [comment]
On a MacBook Air 2013 running Big Sur 11.1 and npm 7.0.15, it succeeded. Admittedly I am entirely unfamiliar with npm, I got my copy through homebrew.
![Screen Shot 2020-12-17 at 3 51 45 PM](https://user-images.githubusercontent.com/46408578/102548104-107e4880-40b2-11eb-98bd-2a75a6f8fc78.png)

**Comment by maxfarseer** [comment]
thank you, I also asks other developers. Looks like it is an issue on my machine. Let's close it.
