### ISSUE TITLE
Doc/Poll Request: Priorities on Feature/Bug-fix

### ISSUE THREAD

**Issue by ishmum123** [elm/compiler#2169]
**Quick Summary:** 

I am quite keen on knowing what are top N feature elm users request and top N bugs elm users would want to be solved. It would be really helpful if we had a poll of some sorts publicly displayed. Apologies if that already exists

**Comment by evancz** [comment]
I recently posted https://github.com/elm/compiler/blob/master/roadmap.md about what I am working on. I think making such a list could be valuable though. Please DM me on slack if you construct such a list, especially if you have organized issues and PRs that do not require any further design work.
