### ISSUE TITLE
Bug in type inference

### ISSUE THREAD

**Issue by akoppela** [elm/compiler#2170]
**Quick Summary:**
Seems like there is a bug in type inference. `r1` and `r2` should have identical types.

## SSCCE

```elm
module TypeInferenceBug exposing (..)

import Url.Parser as P exposing ((</>), Parser)

sum p1 p2 =
    P.map (+) (p1 </> p2)

r1 : Parser (Int -> a) a
r1 =
    P.int
        |> sum P.int
        |> sum P.int

r2 : Parser (Int -> b) b
r2 =
    [ P.int, P.int ]
        |> List.foldl sum P.int
```

- **Elm:** 0.19.1
- **Browser:** Any
- **Operating System:** Any

## Additional Details

The compiler throws an error for `r2`.

```
Something is off with the body of the `r2` definition:

30|>    [ P.int, P.int ]
31|>        |> List.foldl sum P.int

The body is:

    Parser (Int -> Int) Int

But the type annotation on `r2` says it should be:

    Parser (Int -> b) b
```

I found a fix for this as well. Mapping with `identity` function resolves the issue. 

```
r2 : Parser (Int -> b) b
r2 =
    [ P.int, P.int ]
        |> List.foldl sum P.int
        |> P.map identity
```

**Comment by avh4** [comment]
Can you explain in more detail why you think r1 and r2 should have
identical types?   I do see a difference between them in that in r1, the
two calls to `sum` will have different resolved types, whereas in r2, both
calls to `sum` must necessarily have the same concrete type.

**Comment by akoppela** [comment]
Sure, from the `List` module docs

```
So `foldl step state [1,2,3]` is like saying:

state
  |> step 1
  |> step 2
  |> step 3
```

which means that
```
    [ P.int, P.int ]
        |> List.foldl sum P.int
```
equals to
```
    P.int
        |> sum P.int
        |> sum P.int
```

Where do you see the difference?

**Comment by avh4** [comment]
In the fully written-out version, each instance of `step` (or in the
original example, `sum`) can resolve to a different concrete type, but the
use of foldl forces all the instances to have the same concrete type.

You can see this when you add type annotations:

```
sum1 :
    P.Parser (Int -> Int -> Int) (Int -> Int)
    -> P.Parser (Int -> Int) Int
    -> P.Parser (Int -> Int) Int
sum1 p1 p2 =
    P.map (+) (p1 </> p2)


sum2 :
    P.Parser (Int -> Int -> Int) (Int -> Int)
    -> P.Parser (Int -> Int) Int
    -> P.Parser (Int -> a) a
sum2 p1 p2 =
    P.map (+) (p1 </> p2)


t1 : P.Parser (Int -> a) a
t1 =
    P.int
        |> sum1 P.int
        |> sum1 P.int
        |> sum2 P.int


t2 : P.Parser (Int -> a) a
t2 =
    [ P.int, P.int, P.int ]
        |> List.foldl sum1 P.int
        |> P.map identity
```

Note that in `t1` (similar to your original `r1`), the final call to `sum2`
cannot be replaced with `sum1`.  The final call does indeed need to have a
different type to match the `Parser (Int -> a) a` annotation that is given,
which also explains the need for `P.map identity` in `t2` (because the
argument to foldl will always be solved to have `sum1`'s type, and thus the
final call to it cannot leave `a` free).

**Comment by akoppela** [comment]
I do understand that under the hood `P.Parser (Int -> a) a` and `P.Parser (Int -> Int) Int` in the end are equal in eyes of Parser. It's probably a specific of the impementation for the Url.Parser module. E.g. this is not true for compiler

```
t1 : (Int -> Int) -> Int -> a
t1 =
    identity
```
It does want `a` to be `Int`. But that is true for Url.Parser map function.

This is valid.
```
p : Parser (Int -> Int) Int
p =
    P.int

t : Parser (Int -> a) a
t =
    P.map identity p
```

**Comment by akoppela** [comment]
Or a more close example

This is not valid.
```
l : List (Int -> Int)
l =
    []

t : List (Int -> a)
t =
    List.map identity l
```

**Comment by evancz** [comment]
I think the original case should error. If you think there are cases here that should not error, please open an issue about those specific SSCCEs. I think all the cases mentioned here are working alright though. For example:

```
p : Parser (Int -> Int) Int

-- P.map : a -> Parser a b -> Parser (b -> c) c
-- P.map identity : Parser (t1 -> t1) b -> Parser (b -> c) c
-- P.map identity p : Parser (Int -> c) c
```

It seems like the root issue is just that it's freaky how the types work with the URL parsers.

**Comment by akoppela** [comment]
Yes, indeed it’s about Url.Parser specifics. So no issue here.
