### ISSUE TITLE
https://package.elm-lang.org responds 502 Bad Gateway

### ISSUE THREAD

**Issue by lrworth** [elm/compiler#2191]
**Quick Summary:** https://package.elm-lang.org responds 502 Bad Gateway, which breaks a lot of elm tooling.

**Comment by vibosxD** [comment]
Yup same :(

**Comment by evancz** [comment]
Got it back up soon after I heard reports on Twitter and Slack, but I am just seeing the issue reported here. It's back up! Did some additional maintenance on Saturday to try to protect against the root issue, which seems to have been a misbehaving web crawler.
