### ISSUE TITLE
elm init gives 405

### ISSUE THREAD

**Issue by GuillotJessica** [elm/compiler#2192]
**Quick Summary:** ???

I need the list of published packages before I can start initializing projects,
so I tried to fetch:

    https://package.elm-lang.org/all-packages

But it came back as 405 Not Allowed

This may mean some online endpoint changed in an unexpected way, so if does not
seem like something on your side is causing this (e.g. firewall) please report
this to https://github.com/elm/compiler/issues with your operating system, Elm
version, the command you ran, the terminal output, and any additional
information that can help others reproduce the error!

## SSCCE
- **elm i just installed it using curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
- **Operating System:**Linux Mint

**Comment by evancz** [comment]
Thank you for the report!

I am doing some website maintenance that seems to have caused this. It works at the moment, but it may be flaky as I try to figure out why that link was available through browsers but not through `elm init`. I'll report back when I figure it out!

**Comment by GuillotJessica** [comment]
it worked, thank you

**Comment by evancz** [comment]
Sorry for the trouble with this!

I have been trying to make the package website a little faster, but it looks like I made a change that was incompatible with the `elm init` code. It makes a `POST` request for some data, and the server only wanted `GET` requests. It should be fixed now though!
