### ISSUE TITLE
install on linux

### ISSUE THREAD

**Issue by dullbananas** [elm/compiler#2198]
The installation instructions tell me to use the `gnuzip` command which is usually not installed already

**Comment by lydell** [comment]
@dullbananas Do you mean these instructions: https://github.com/elm/compiler/blob/770071accf791e8171440709effe71e78a9ab37c/installers/linux/README.md ?

If so, they say <strong>gun</strong>zip, not gnu. There’s gzip for zipping and “g-unzip” for unzipping…
