### ISSUE TITLE
npm: Change request to other packages

### ISSUE THREAD

**Issue by massongit** [elm/compiler#2229]
The npm package `request` is under maintenance mode: https://github.com/request/request/issues/3142
Therefore, you need to change `request` to other packages.

Alternative libraries to request: https://github.com/request/request/issues/3143

**Comment by sporto** [comment]
`Request 2.88.2` depends on `form-data 2.3.3`, which depends on `json-schema 0.2.3`

json-schema 0.2.3 has a critical vulnerability:
https://github.com/advisories/GHSA-896r-f27r-55mw

Which is a problem for using Elm. If you org needs to comply with security audits (like us).

So it would be really good to change this

**Comment by lydell** [comment]
FYI: The `request` dependency is being removed in https://github.com/elm/compiler/pull/2287

**Comment by lydell** [comment]
@adrian-gomez I’m not sure I understand what you mean. Could we chat about it on Slack perhaps?
