### ISSUE TITLE
Detect misusage of Debug.log

### ISSUE THREAD

**Issue by Warry** [elm/compiler#2233]
**Quick Summary:** ???

A coworker struggled finding the reason why their `Debug.log` didn't fire anything. The log function was actually assigned to `_`, a common pattern we use in the company, but missing the last parametter. It was actually assigning the identity function to underscore.

Shouldn't it fire some kind of error or warning, as it's probably not intended ? Assigning a function to _ (underscore) could be a compile error, or maybe using Debug.* missing a parameter be forbidden to ensure no silent behaviour ?

It could go in elm-review, but we do not run this on each file save, so I don't know to how much extend this could be as good as a solution.

## SSCCE

```elm
hello =
    let
        _ : a -> a
        _ =
            Debug.log "Hello"
    in
    "world"
```

**Comment by lue-bird** [comment]
Is also discussed in https://github.com/elm/core/issues/1082.
