### ISSUE TITLE
murmur3 package install

### ISSUE THREAD

**Issue by dotnetspec** [elm/compiler#2266]
**Quick Summary:** ???
I am unable to compile as I am having problems with murmur3 package:
```
elm install robinheghan/murmur3
Here is my plan:
  
  Add:
    Skinney/murmur3        2.0.8
    robinheghan/murmur3    1.0.0

Would you like me to update your elm.json accordingly? [Y/n]: 
-- PROBLEM DOWNLOADING PACKAGE -------------------------------------------------

I was trying to download the source code for Skinney/murmur3 2.0.8, so I tried
to fetch:

    https://github.com/Skinney/murmur3/zipball/2.0.8/

But it came back as 404 Not Found
```

## SSCCE

```elm

```

- **Elm:** 0.19.1.
- **Browser:** Firefox 102.0.1 (64 bit)
- **Operating System:** Linux Mint 20+

## Additional Details

I have returned to the project after more that 18 months.
What should I do to fix this error?

Thanks ...

**Comment by jfmengels** [comment]
Hi @dotnetspec

I might be missing some information, but the way I understand it is that you have the `Skinney/murmur3` package in your `elm.json`, but that one does not exist anymore. You should remove it from your `elm.json` before adding something new.

I believe you can just straight up remove the line for `Skinney/murmur3`. If that doesn't work, you could try using the [`elm-json`](https://github.com/zwilias/elm-json#example-uninstalling-a-package) tool to uninstall the package.

Once that it done, I believe that adding `robinheghan/murmur3` should work.

**Comment by dotnetspec** [comment]
Hi @jfmengels ,
If I manually remove the line for Skinney/murmur3 I get:
```
It looks like the dependencies elm.json in were edited by hand (or by a 3rd
party tool) leaving them in an invalid state.
```
If I use elm-json:
```
elm-json uninstall Skinney/murmur3

-- PACKAGE CHANGES READY -------------------------------------------------------

Should I make these changes? yes
Saved updated elm.json!
```
Nothing happens, the file is _not_ updated.
If I manually add robinheghan/murmur3 I get:

```
Dependencies ready!         
-- ERROR IN DEPENDENCIES ---------------------------------------------- elm.json

It looks like the dependencies elm.json in were edited by hand (or by a 3rd
party tool) leaving them in an invalid state.
```
Is there anything else I can try?
Thanks for your help ...

**Comment by dotnetspec** [comment]
Fixed! As mentioned above.
