### ISSUE TITLE
What's the state of the Elm repo?

### ISSUE THREAD

**Issue by NickSeagull** [elm/compiler#2308]
**Quick Summary:** I want to understand why there are no commits since 1+ years.

# Details

Hi, I've been always a fan of Elm and used it here and there. I was wondering why the development hasn't been moving.

I understand that the language is more than stable now, and I can't think of a feature to add to Elm (or at least frontend-wise, frontend as in a compiler frontend) that wouldn't make the language more complex.

But on the other hand, I'm worried that the language innovation just dies here and doesn't keep up with the world.

# Examples:

- Elm generates a JS file that is an IIFE module. I know there are repos that convert that to ESM or CJS, but I think that Elm should just generate ESM by default now.
- There's already a ton of Elm repos that are hacking around to make CLI tools to process data (like Elm files) I think that it's a sign of a community need.
- There are internal features that could be added to the language like on-demand reflection, or a better command management model with the possibility of loading pre-defined action handlers on compile time.
- Monorepo support

# The question

I feel like the project is stale, and although it has innovated so much that it is far away from getting old, I still feel like keeping the movement in innovation and creativity maintains the community growing :)

**Comment by NickSeagull** [comment]
As a follow up from talking on Slack with the community.

Progress has been made, just privately by Evan. He has done amazing things, yet they aren't ready for publishing yet. They will be somewhere soon ready, and a big release will be done.

The decision model of the language is following a BDFL, rather than the community. I was pointed to Gren (https://gren-lang.org/) , an Elm fork that has a different decision model.

Also, I want to give a huge kudos to Evan and all the effort he takes to keep Elm awesome, my concern wasn't about putting more pressure on Evan, but rather to express my desire to remove it by opening the development model a bit.

Thanks to everyone involved in the discussion!  ❤️

**Comment by lue-bird** [comment]
@ggPeti gren's syntax is identical to elm, with tuples removed and record patterns added. Maybe yuo are thinking of roc, stabel or something else?

**Comment by ggPeti** [comment]
@lue-bird yes it seems I was confusing it with another language. I did know however about the lack of tuples and I do rely on them quite often, so that's an inconvenience. In any case, a language is more than just syntax - it's the ecosystem that develops around it that matters. Evan did get some things right that sparked the community to life, but his long standing blockading of getting bugs fixed is destroying it.

**Comment by MarkuBu** [comment]
I still avoid Elm for any project larger than simple practicing projects to learn the concept and functional programming in general.

Elm is great, but the lack of progress and informations keeps me from using Elm.

**Comment by sjalq** [comment]
Sadly Evan is the ultimate Sigma male. He projects as a real leader only to completely reverse position and mumble "I duh wan it" like Jon Snow when actual responsibility emerges from his creations.

**Comment by heyakyra** [comment]
See discussion here: https://discourse.elm-lang.org/t/how-was-the-elm-goto-talk/9150/

**Comment by ggPeti** [comment]
> See discussion here: https://discourse.elm-lang.org/t/how-was-the-elm-goto-talk/9150/9

Yeah wow, can't wait to start using another thing that will have radio silence on fixing the most trivial of bugs.
