### ISSUE TITLE
Elm lacks String -> Number (and Number -> String) functions

### ISSUE THREAD

**Issue by joeyadams** [elm/compiler#30]
Elm does not seem to have a built-in function for converting a string to a number.  I don't think it has a function for converting a number to a string, either (e.g. `plainText $ show n ++ " bottles of beer on the wall"`).

To address the former, we could add the following functions, perhaps to Prelude, Foreign.JavaScript, or even a new "Numeric" module.

```
parseInt     :: String -> Maybe Int
parseIntBase :: Int -> String -> Maybe Int
parseFloat   :: String -> Maybe Float
```

Here is the corresponding JavaScript.  We must be careful not to shadow the system `parseInt` and `parseFloat` when defining our functions.

```
function parseIntBase(base) {
    return function(str) {
        var n = parseInt(castStringToJSString(str), base);
        return isNaN(n) ? Nothing : Just(n);
    };
}

...

return {
    parseInt:     parseIntBase(10),
    parseIntBase: parseIntBase,
    parseFloat: function(str) {
        var n = parseFloat(castStringToJSString(str));
        return isNaN(n) ? Nothing : Just(n);
    }
};
```

Would something like this be good?  Or did you have bigger plans, like a `read` function whose return type determines behavior.

**Comment by bbugh** [comment]
Since this is still a top Google search result for parsing ints from strings in Elm, `readInt` has been deprecated. The current function is `String.toInt : String -> Result String Int`. See the docs here: http://package.elm-lang.org/packages/elm-lang/core/2.1.0/String#toInt

**Comment by rafaeleyng** [comment]
I came here looking for a way to convert Numbert -> String, but no cigar

**Comment by mgold** [comment]
@rafaeleyng Use `toString : a -> String`.

**Comment by dubert** [comment]
@mgold how can converting a `number` to a `String` be done now that `toString` has been removed?

**Comment by mgold** [comment]
Elm 0.19's `String` module has [functions](https://package.elm-lang.org/packages/elm/core/latest/String#int-conversions) to convert in both directions.

**Comment by dubert** [comment]
@mgold but only if you know whether it is an `Int` or a `Float`. I'm trying to convert a `number` to a `String` and Elm has no way of detecting whether a value is an `Int` or a `Float`. You have to know it beforehand.

**Comment by mgold** [comment]
If you have further questions, please take them over to the [discourse](https://discourse.elm-lang.org).
