### ISSUE TITLE
Flattening Signals?

### ISSUE THREAD

**Issue by micmarsh** [elm/compiler#440]
Is there any way to write a function of the type Signal (Signal a) -> Signal a, to "flatten" a signal of Signals into a single Signal?

I want to use WebSocket.connect on a signal that provides the current location.host from javascript, since that varies depending on where the app is currently running. I can use `lift (\url -> connect url someInputStrings) urlHost`, which gives a Signal (Signal String). If there's another way to accomplish this, I'd be open to that too!

**Comment by lexwraith** [comment]
@pthariensflame - your link to Evan's Thesis leads to some bizarre page loaded with popups - could we get the new link and remove the old one? It currently points to:

http://www.testblogpleaseignore.com/wp-content/uploads/2012/04/thesis.pdf

**Comment by pthariensflame** [comment]
@lexwraith I don't want to edit it in the interest of preserving history, but the current link is http://elm-lang.org/papers/concurrent-frp.pdf.

**Comment by lexwraith** [comment]
@pthariensflame Great, thanks!
