### ISSUE TITLE
0.14 - implicit Int to Float conversion no longer occurring for named values

### ISSUE THREAD

**Issue by WillSewell** [elm/compiler#852]
In 0.13, this would work fine, but I am not getting a type mismatch error. I had thought we might now need to do explicit conversion, but I couldn't find any functions for this in the core library.

```
import Text (asText)

x : Int
x = 1

main = asText <| x * 0.5
```

produces

```
Type mismatch between the following types on line 6, column 18 to 25:

        Int

        Float

    It is related to the following expression:

        x * 0.5
```

**Comment by Natim** [comment]
I just encountered the same issue. I guess we could improve the documentation definition of `round`, `toFloat` and `truncate` to explicitly add search engine questions `convert a Float into an Int`, `convert an Int into a Float`, `truncate a Float into an Int`

Now that I know that I should look at the [Number Conversion](http://package.elm-lang.org/packages/elm-lang/core/latest/Basics#number-conversions) documentation.

Now I will remember it, but before I had a hard time finding the information.
